.TH "Referencia del directorio config_43xx_m0app" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio config_43xx_m0app \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBconfig_43xx_m0app/cmsis_43xx_m0app\&.h\fP"
.br
.ti -1c
.RI "archivo \fBm0app/sys_config\&.h\fP"
.br
.in -1c
