.TH "Referencia del directorio config_43xx" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio config_43xx \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBconfig_43xx/cmsis_43xx\&.h\fP"
.br
.ti -1c
.RI "archivo \fBsys_config\&.h\fP"
.br
.in -1c
