.TH "Referencia del directorio lpc" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio lpc \- 
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBconfig_43xx\fP"
.br
.ti -1c
.RI "directorio \fBconfig_43xx_m0app\fP"
.br
.ti -1c
.RI "directorio \fBconfig_43xx_m0sub\fP"
.br
.ti -1c
.RI "directorio \fBiap\fP"
.br
.ti -1c
.RI "directorio \fBinc\fP"
.br
.ti -1c
.RI "directorio \fBsrc\fP"
.br
.in -1c
