.TH "Referencia del directorio inc" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio inc \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBhardware\&.h\fP"
.br
.RI "\fIDeclaraciones de funciones y constantes simbólicas correspondientes con la EDU-CIAA NXP\&. \fP"
.ti -1c
.RI "archivo \fBregistro\&.h\fP"
.br
.ti -1c
.RI "archivo \fButils\&.h\fP"
.br
.RI "\fIDiversas funciones de utilidad simplificar el desarrollo de software para aplicaciones embebidas\&. \fP"
.in -1c
