.TH "Referencia del directorio src" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBcrp\&.c\fP"
.br
.ti -1c
.RI "archivo \fBhardware\&.c\fP"
.br
.ti -1c
.RI "archivo \fBmain\&.c\fP"
.br
.ti -1c
.RI "archivo \fBregistro\&.c\fP"
.br
.ti -1c
.RI "archivo \fBstartUp\&.c\fP"
.br
.ti -1c
.RI "archivo \fButils\&.c\fP"
.br
.in -1c
