.TH "_mci_card_struct" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mci_card_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sdmmc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBsdif_device\fP \fBsdif_dev\fP"
.br
.ti -1c
.RI "\fBSDMMC_CARD_T\fP \fBcard_info\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 86 del archivo sdmmc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBSDMMC_CARD_T\fP card_info"

.PP
Definición en la línea 88 del archivo sdmmc_18xx_43xx\&.h\&.
.SS "\fBsdif_device\fP sdif_dev"

.PP
Definición en la línea 87 del archivo sdmmc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
