.TH "_sdif_device" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sdif_device \- SDIO device type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sdif_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBpSDMMC_DMA_T\fP \fBmci_dma_dd\fP [1+(0x10000/MCI_DMADES1_MAXTR)]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
SDIO device type\&. 
.PP
Definición en la línea 252 del archivo sdif_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBpSDMMC_DMA_T\fP mci_dma_dd[1+(0x10000/MCI_DMADES1_MAXTR)]"

.PP
Definición en la línea 254 del archivo sdif_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
