.TH "ADC_CLOCK_SETUP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_CLOCK_SETUP_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBadcRate\fP"
.br
.ti -1c
.RI "uint8_t \fBbitsAccuracy\fP"
.br
.ti -1c
.RI "bool \fBburstMode\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Clock setup structure for ADC controller passed to the initialize function 
.PP
Definición en la línea 134 del archivo adc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t adcRate"
ADC rate 
.PP
Definición en la línea 135 del archivo adc_18xx_43xx\&.h\&.
.SS "uint8_t bitsAccuracy"
ADC bit accuracy 
.PP
Definición en la línea 136 del archivo adc_18xx_43xx\&.h\&.
.SS "bool burstMode"
ADC Burt Mode 
.PP
Definición en la línea 137 del archivo adc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
