.TH "arm_pid_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_pid_instance_f32 \- Instance structure for the floating-point PID Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBfloat32_t\fP \fBA0\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBA1\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBA2\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBstate\fP [3]"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKp\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKi\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKd\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point PID Control\&. 
.PP
Definición en la línea 1767 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBfloat32_t\fP A0"
The derived gain, A0 = Kp + Ki + Kd \&. 
.PP
Definición en la línea 1769 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP A1"
The derived gain, A1 = -Kp - 2Kd\&. 
.PP
Definición en la línea 1770 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP A2"
The derived gain, A2 = Kd \&. 
.PP
Definición en la línea 1771 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP Kd"
The derivative gain\&. 
.PP
Definición en la línea 1775 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP Ki"
The integral gain\&. 
.PP
Definición en la línea 1774 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP Kp"
The proportional gain\&. 
.PP
Definición en la línea 1773 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP state[3]"
The state array of length 3\&. 
.PP
Definición en la línea 1772 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
