.TH "arm_matrix_instance_q31" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_matrix_instance_q31 \- Instance structure for the Q31 matrix structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint16_t \fBnumRows\fP"
.br
.ti -1c
.RI "uint16_t \fBnumCols\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpData\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the Q31 matrix structure\&. 
.PP
Definición en la línea 1429 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint16_t numCols"
number of columns of the matrix\&. 
.PP
Definición en la línea 1432 del archivo arm_math\&.h\&.
.SS "uint16_t numRows"
number of rows of the matrix\&. 
.PP
Definición en la línea 1431 del archivo arm_math\&.h\&.
.SS "\fBq31_t\fP* pData"
points to the data of the matrix\&. 
.PP
Definición en la línea 1433 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
