.TH "arm_cfft_radix2_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_cfft_radix2_instance_f32 \- Instance structure for the floating-point CFFT/CIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint16_t \fBfftLen\fP"
.br
.ti -1c
.RI "uint8_t \fBifftFlag\fP"
.br
.ti -1c
.RI "uint8_t \fBbitReverseFlag\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "uint16_t * \fBpBitRevTable\fP"
.br
.ti -1c
.RI "uint16_t \fBtwidCoefModifier\fP"
.br
.ti -1c
.RI "uint16_t \fBbitRevFactor\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBonebyfftLen\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point CFFT/CIFFT function\&. 
.PP
Definición en la línea 2066 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t bitReverseFlag"
flag that enables (bitReverseFlag=1) or disables (bitReverseFlag=0) bit reversal of output\&. 
.PP
Definición en la línea 2070 del archivo arm_math\&.h\&.
.SS "uint16_t bitRevFactor"
bit reversal modifier that supports different size FFTs with the same bit reversal table\&. 
.PP
Definición en la línea 2074 del archivo arm_math\&.h\&.
.SS "uint16_t fftLen"
length of the FFT\&. 
.PP
Definición en la línea 2068 del archivo arm_math\&.h\&.
.SS "uint8_t ifftFlag"
flag that selects forward (ifftFlag=0) or inverse (ifftFlag=1) transform\&. 
.PP
Definición en la línea 2069 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP onebyfftLen"
value of 1/fftLen\&. 
.PP
Definición en la línea 2075 del archivo arm_math\&.h\&.
.SS "uint16_t* pBitRevTable"
points to the bit reversal table\&. 
.PP
Definición en la línea 2072 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pTwiddle"
points to the Twiddle factor table\&. 
.PP
Definición en la línea 2071 del archivo arm_math\&.h\&.
.SS "uint16_t twidCoefModifier"
twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table\&. 
.PP
Definición en la línea 2073 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
