.TH "arm_linear_interp_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_linear_interp_instance_f32 \- Instance structure for the floating-point Linear Interpolate function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBnValues\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBx1\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBxSpacing\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpYData\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point Linear Interpolate function\&. 
.PP
Definición en la línea 1841 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t nValues"
nValues 
.PP
Definición en la línea 1843 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pYData"
pointer to the table of Y values 
.PP
Definición en la línea 1846 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP x1"
x1 
.PP
Definición en la línea 1844 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP xSpacing"
xSpacing 
.PP
Definición en la línea 1845 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
