.TH "arm_lms_norm_instance_q15" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_lms_norm_instance_q15 \- Instance structure for the Q15 normalized LMS filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint16_t \fBnumTaps\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpCoeffs\fP"
.br
.ti -1c
.RI "\fBq15_t\fP \fBmu\fP"
.br
.ti -1c
.RI "uint8_t \fBpostShift\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBrecipTable\fP"
.br
.ti -1c
.RI "\fBq15_t\fP \fBenergy\fP"
.br
.ti -1c
.RI "\fBq15_t\fP \fBx0\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the Q15 normalized LMS filter\&. 
.PP
Definición en la línea 4264 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBq15_t\fP energy"
saves previous frame energy\&. 
.PP
Definición en la línea 4272 del archivo arm_math\&.h\&.
.SS "\fBq15_t\fP mu"
step size that controls filter coefficient updates\&. 
.PP
Definición en la línea 4269 del archivo arm_math\&.h\&.
.SS "uint16_t numTaps"
Number of coefficients in the filter\&. 
.PP
Definición en la línea 4266 del archivo arm_math\&.h\&.
.SS "\fBq15_t\fP* pCoeffs"
points to the coefficient array\&. The array is of length numTaps\&. 
.PP
Definición en la línea 4268 del archivo arm_math\&.h\&.
.SS "uint8_t postShift"
bit shift applied to coefficients\&. 
.PP
Definición en la línea 4270 del archivo arm_math\&.h\&.
.SS "\fBq15_t\fP* pState"
points to the state variable array\&. The array is of length numTaps+blockSize-1\&. 
.PP
Definición en la línea 4267 del archivo arm_math\&.h\&.
.SS "\fBq15_t\fP* recipTable"
Points to the reciprocal initial value table\&. 
.PP
Definición en la línea 4271 del archivo arm_math\&.h\&.
.SS "\fBq15_t\fP x0"
saves previous input sample\&. 
.PP
Definición en la línea 4273 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
