.TH "arm_biquad_cascade_df2T_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_biquad_cascade_df2T_instance_f32 \- Instance structure for the floating-point transposed direct form II Biquad cascade filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBnumStages\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpCoeffs\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point transposed direct form II Biquad cascade filter\&. 
.PP
Definición en la línea 3689 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t numStages"
number of 2nd order stages in the filter\&. Overall order is 2*numStages\&. 
.PP
Definición en la línea 3691 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pCoeffs"
points to the array of coefficients\&. The array is of length 5*numStages\&. 
.PP
Definición en la línea 3693 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pState"
points to the array of state coefficients\&. The array is of length 2*numStages\&. 
.PP
Definición en la línea 3692 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
