.TH "arm_cfft_radix2_instance_q31" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_cfft_radix2_instance_q31 \- Instance structure for the Radix-2 Q31 CFFT/CIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint16_t \fBfftLen\fP"
.br
.ti -1c
.RI "uint8_t \fBifftFlag\fP"
.br
.ti -1c
.RI "uint8_t \fBbitReverseFlag\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "uint16_t * \fBpBitRevTable\fP"
.br
.ti -1c
.RI "uint16_t \fBtwidCoefModifier\fP"
.br
.ti -1c
.RI "uint16_t \fBbitRevFactor\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the Radix-2 Q31 CFFT/CIFFT function\&. 
.PP
Definición en la línea 2015 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t bitReverseFlag"
flag that enables (bitReverseFlag=1) or disables (bitReverseFlag=0) bit reversal of output\&. 
.PP
Definición en la línea 2019 del archivo arm_math\&.h\&.
.SS "uint16_t bitRevFactor"
bit reversal modifier that supports different size FFTs with the same bit reversal table\&. 
.PP
Definición en la línea 2023 del archivo arm_math\&.h\&.
.SS "uint16_t fftLen"
length of the FFT\&. 
.PP
Definición en la línea 2017 del archivo arm_math\&.h\&.
.SS "uint8_t ifftFlag"
flag that selects forward (ifftFlag=0) or inverse (ifftFlag=1) transform\&. 
.PP
Definición en la línea 2018 del archivo arm_math\&.h\&.
.SS "uint16_t* pBitRevTable"
points to the bit reversal table\&. 
.PP
Definición en la línea 2021 del archivo arm_math\&.h\&.
.SS "\fBq31_t\fP* pTwiddle"
points to the Twiddle factor table\&. 
.PP
Definición en la línea 2020 del archivo arm_math\&.h\&.
.SS "uint16_t twidCoefModifier"
twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table\&. 
.PP
Definición en la línea 2022 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
