.TH "arm_bilinear_interp_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_bilinear_interp_instance_f32 \- Instance structure for the floating-point bilinear interpolation function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint16_t \fBnumRows\fP"
.br
.ti -1c
.RI "uint16_t \fBnumCols\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpData\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point bilinear interpolation function\&. 
.PP
Definición en la línea 1853 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint16_t numCols"
number of columns in the data table\&. 
.PP
Definición en la línea 1856 del archivo arm_math\&.h\&.
.SS "uint16_t numRows"
number of rows in the data table\&. 
.PP
Definición en la línea 1855 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pData"
points to the data table\&. 
.PP
Definición en la línea 1857 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
