.TH "arm_rfft_fast_instance_f32" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_rfft_fast_instance_f32 \- Instance structure for the floating-point RFFT/RIFFT function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBarm_cfft_instance_f32\fP \fBSint\fP"
.br
.ti -1c
.RI "uint16_t \fBfftLenRFFT\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpTwiddleRFFT\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Instance structure for the floating-point RFFT/RIFFT function\&. 
.PP
Definición en la línea 2224 del archivo arm_math\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint16_t fftLenRFFT"
length of the real sequence 
.PP
Definición en la línea 2227 del archivo arm_math\&.h\&.
.SS "\fBfloat32_t\fP* pTwiddleRFFT"
Twiddle factors real stage 
.PP
Definición en la línea 2228 del archivo arm_math\&.h\&.
.SS "\fBarm_cfft_instance_f32\fP Sint"
Internal CFFT structure\&. 
.PP
Definición en la línea 2226 del archivo arm_math\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
