.TH "atimer_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atimer_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_ATIMER_Init\fP (\fBLPC_ATIMER_T\fP *pATIMER, uint32_t PresetValue)"
.br
.RI "\fIInitialize Alarm Timer\&. \fP"
.ti -1c
.RI "void \fBChip_ATIMER_DeInit\fP (\fBLPC_ATIMER_T\fP *pATIMER)"
.br
.RI "\fIClose ATIMER device\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
