.TH "CCAN_IF_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCAN_IF_T \- CCAN message interface register block structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ccan_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMDREQ\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMDMSK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMSK1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMSK2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBARB1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBARB2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDA1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDA2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDB1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDB2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [13]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
CCAN message interface register block structure\&. 
.PP
Definición en la línea 47 del archivo ccan_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t ARB1"
Message interface arbitration 1 
.PP
Definición en la línea 52 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t ARB2"
Message interface arbitration 2 
.PP
Definición en la línea 53 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t CMDMSK"
Message interface command mask 
.PP
Definición en la línea 49 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t CMDREQ"
< C_CAN message interface Structure Message interface command request 
.PP
Definición en la línea 48 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t DA1"
Message interface data A1 
.PP
Definición en la línea 55 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t DA2"
Message interface data A2 
.PP
Definición en la línea 56 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t DB1"
Message interface data B1 
.PP
Definición en la línea 57 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t DB2"
Message interface data B2 
.PP
Definición en la línea 58 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t MCTRL"
Message interface message control 
.PP
Definición en la línea 54 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t MSK1"
Message interface mask 1 
.PP
Definición en la línea 50 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t MSK2"
Message interface mask 2 
.PP
Definición en la línea 51 del archivo ccan_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED[13]"

.PP
Definición en la línea 59 del archivo ccan_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
