.TH "CCU_CFGSTAT_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCU_CFGSTAT_T \- CCU clock config/status register pair\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cguccu_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFG\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSTAT\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
CCU clock config/status register pair\&. 
.PP
Definición en la línea 81 del archivo cguccu_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t CFG"
CCU clock configuration register 
.PP
Definición en la línea 82 del archivo cguccu_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t STAT"
CCU clock status register 
.PP
Definición en la línea 83 del archivo cguccu_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
