.TH "CGU_PLL_REG_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGU_PLL_REG_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cguccu_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__I\fP uint32_t \fBPLL_STAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPLL_CTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPLL_MDIV\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPLL_NP_DIV\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
PLL register block 
.PP
Definición en la línea 56 del archivo cguccu_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t PLL_CTRL"
PLL control register 
.PP
Definición en la línea 58 del archivo cguccu_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t PLL_MDIV"
PLL M-divider register 
.PP
Definición en la línea 59 del archivo cguccu_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t PLL_NP_DIV"
PLL N/P-divider register 
.PP
Definición en la línea 60 del archivo cguccu_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t PLL_STAT"
PLL status register 
.PP
Definición en la línea 57 del archivo cguccu_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
