.TH "CGU_USBAUDIO_PLL_SETUP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGU_USBAUDIO_PLL_SETUP_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBctrl\fP"
.br
.ti -1c
.RI "uint32_t \fBmdiv\fP"
.br
.ti -1c
.RI "uint32_t \fBndiv\fP"
.br
.ti -1c
.RI "uint32_t \fBfract\fP"
.br
.ti -1c
.RI "uint32_t \fBfreq\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Structure for setting up the USB or audio PLL 
.PP
Definición en la línea 319 del archivo clock_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t ctrl"

.PP
Definición en la línea 320 del archivo clock_18xx_43xx\&.h\&.
.SS "uint32_t fract"

.PP
Definición en la línea 323 del archivo clock_18xx_43xx\&.h\&.
.SS "uint32_t freq"

.PP
Definición en la línea 324 del archivo clock_18xx_43xx\&.h\&.
.SS "uint32_t mdiv"

.PP
Definición en la línea 321 del archivo clock_18xx_43xx\&.h\&.
.SS "uint32_t ndiv"

.PP
Definición en la línea 322 del archivo clock_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
