.TH "cguccu_18xx_43xx.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cguccu_18xx_43xx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip_clocks\&.h'\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBCGU_PLL_REG_T\fP"
.br
.ti -1c
.RI "struct \fBLPC_CGU_T\fP"
.br
.RI "\fILPC18XX/43XX CGU register block structure\&. \fP"
.ti -1c
.RI "struct \fBCCU_CFGSTAT_T\fP"
.br
.RI "\fICCU clock config/status register pair\&. \fP"
.ti -1c
.RI "struct \fBLPC_CCU1_T\fP"
.br
.RI "\fICCU1 register block structure\&. \fP"
.ti -1c
.RI "struct \fBLPC_CCU2_T\fP"
.br
.RI "\fICCU2 register block structure\&. \fP"
.in -1c
.in +1c
.ti -1c
.RI "enum \fBCHIP_CGU_USB_AUDIO_PLL\fP { \fBCGU_USB_PLL\fP, \fBCGU_AUDIO_PLL\fP }"
.br
.ti -1c
.RI "typedef enum \fBCHIP_CGU_USB_AUDIO_PLL\fP \fBCHIP_CGU_USB_AUDIO_PLL_T\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
