.TH "CHIP_FPU_CMX" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHIP_FPU_CMX \- CHIP: FPU initialization
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBfpuInit\fP (void)"
.br
.RI "\fIEarly initialization of the FPU\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Cortex FPU initialization 
.SH "Documentación de las funciones"
.PP 
.SS "void fpuInit (void)"

.PP
Early initialization of the FPU\&. 
.PP
\fBDevuelve:\fP
.RS 4
Nothing 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
