.TH "Chip_SSP_DATA_SETUP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chip_SSP_DATA_SETUP_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssp_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "void * \fBtx_data\fP"
.br
.ti -1c
.RI "uint32_t \fBtx_cnt\fP"
.br
.ti -1c
.RI "void * \fBrx_data\fP"
.br
.ti -1c
.RI "uint32_t \fBrx_cnt\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 470 del archivo ssp_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t length"
Length of transfer data 
.PP
Definición en la línea 475 del archivo ssp_18xx_43xx\&.h\&.
.SS "uint32_t rx_cnt"
Receive counter 
.PP
Definición en la línea 474 del archivo ssp_18xx_43xx\&.h\&.
.SS "void* rx_data"
Pointer to transmit data 
.PP
Definición en la línea 473 del archivo ssp_18xx_43xx\&.h\&.
.SS "uint32_t tx_cnt"
Transmit counter 
.PP
Definición en la línea 472 del archivo ssp_18xx_43xx\&.h\&.
.SS "void* tx_data"
Pointer to transmit data 
.PP
Definición en la línea 471 del archivo ssp_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
