.TH "CLK_PERIPH_TO_BASE_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLK_PERIPH_TO_BASE_T \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBCHIP_CCU_CLK_T\fP \fBclkstart\fP"
.br
.ti -1c
.RI "\fBCHIP_CCU_CLK_T\fP \fBclkend\fP"
.br
.ti -1c
.RI "\fBCHIP_CGU_BASE_CLK_T\fP \fBclkbase\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 38 del archivo clock_18xx_43xx\&.c\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBCHIP_CGU_BASE_CLK_T\fP clkbase"

.PP
Definición en la línea 41 del archivo clock_18xx_43xx\&.c\&.
.SS "\fBCHIP_CCU_CLK_T\fP clkend"

.PP
Definición en la línea 40 del archivo clock_18xx_43xx\&.c\&.
.SS "\fBCHIP_CCU_CLK_T\fP clkstart"

.PP
Definición en la línea 39 del archivo clock_18xx_43xx\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
