.TH "CLK_BASE_STATES" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLK_BASE_STATES \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBCHIP_CGU_BASE_CLK_T\fP \fBclk\fP"
.br
.ti -1c
.RI "\fBCHIP_CGU_CLKIN_T\fP \fBclkin\fP"
.br
.ti -1c
.RI "bool \fBautoblock_enab\fP"
.br
.ti -1c
.RI "bool \fBpowerdn\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 39 del archivo sysinit_18xx_43xx\&.c\&.
.SH "Documentación de los campos"
.PP 
.SS "bool autoblock_enab"

.PP
Definición en la línea 42 del archivo sysinit_18xx_43xx\&.c\&.
.SS "\fBCHIP_CGU_BASE_CLK_T\fP clk"

.PP
Definición en la línea 40 del archivo sysinit_18xx_43xx\&.c\&.
.SS "\fBCHIP_CGU_CLKIN_T\fP clkin"

.PP
Definición en la línea 41 del archivo sysinit_18xx_43xx\&.c\&.
.SS "bool powerdn"

.PP
Definición en la línea 43 del archivo sysinit_18xx_43xx\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
