.TH "CMSIS_SIMD_intrinsics" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SIMD_intrinsics \- CMSIS SIMD IntrinsicsAccess to dedicated SIMD instructions 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
