.TH "CMSIS_NVIC" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_NVIC \- Nested Vectored Interrupt Controller (NVIC)
.PP
Type definitions for the NVIC Registers\&.  

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.RI "\fIStructure type to access the Nested Vectored Interrupt Controller (NVIC)\&. \fP"
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL << NVIC_STIR_INTID_Pos)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL << NVIC_STIR_INTID_Pos)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL << NVIC_STIR_INTID_Pos)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Type definitions for the NVIC Registers\&. 


.SH "Documentación de los 'defines'"
.PP 
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL << NVIC_STIR_INTID_Pos)"
STIR: INTLINESNUM Mask 
.PP
Definición en la línea 306 del archivo core_sc300\&.h\&.
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL << NVIC_STIR_INTID_Pos)"
STIR: INTLINESNUM Mask 
.PP
Definición en la línea 315 del archivo core_cm3\&.h\&.
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL << NVIC_STIR_INTID_Pos)"
STIR: INTLINESNUM Mask 
.PP
Definición en la línea 355 del archivo core_cm4\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0"
STIR: INTLINESNUM Position 
.PP
Definición en la línea 305 del archivo core_sc300\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0"
STIR: INTLINESNUM Position 
.PP
Definición en la línea 314 del archivo core_cm3\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0"
STIR: INTLINESNUM Position 
.PP
Definición en la línea 354 del archivo core_cm4\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
