.TH "CMSIS_CORE" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_CORE \- Status and Control Registers
.PP
Core Register type definitions\&.  

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "union \fBAPSR_Type\fP"
.br
.RI "\fIUnion type to access the Application Program Status Register (APSR)\&. \fP"
.ti -1c
.RI "union \fBIPSR_Type\fP"
.br
.RI "\fIUnion type to access the Interrupt Program Status Register (IPSR)\&. \fP"
.ti -1c
.RI "union \fBxPSR_Type\fP"
.br
.RI "\fIUnion type to access the Special-Purpose Program Status Registers (xPSR)\&. \fP"
.ti -1c
.RI "union \fBCONTROL_Type\fP"
.br
.RI "\fIUnion type to access the Control Registers (CONTROL)\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Core Register type definitions\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
