.TH "CMSIS_18XX_COMMON" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_18XX_COMMON \- CHIP: LPC18xx Cortex CMSIS definitions
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fB__CM3_REV\fP   0x0201"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   1"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   3"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   0"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "#define __CM3_REV   0x0201"

.PP
Definición en la línea 66 del archivo cmsis_18xx\&.h\&.
.SS "#define __FPU_PRESENT   0"
FPU present or not 
.PP
Definición en la línea 70 del archivo cmsis_18xx\&.h\&.
.SS "#define __MPU_PRESENT   1"
MPU present or not 
.PP
Definición en la línea 67 del archivo cmsis_18xx\&.h\&.
.SS "#define __NVIC_PRIO_BITS   3"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 68 del archivo cmsis_18xx\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 69 del archivo cmsis_18xx\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
