.TH "CMSIS_43XX_M0_COMMON" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_43XX_M0_COMMON \- CHIP: LPC43xx (M0 Core) Cortex CMSIS definitions
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   2"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   2"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   2"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   0"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   2"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   0"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "#define __FPU_PRESENT   0"
FPU present or not 
.PP
Definición en la línea 70 del archivo config_43xx_m0app/cmsis_43xx_m0app\&.h\&.
.SS "#define __FPU_PRESENT   0"
FPU present or not 
.PP
Definición en la línea 70 del archivo config_43xx_m0sub/cmsis_43xx_m0sub\&.h\&.
.SS "#define __FPU_PRESENT   0"
FPU present or not 
.PP
Definición en la línea 70 del archivo inc/cmsis_43xx_m0sub\&.h\&.
.SS "#define __FPU_PRESENT   0"
FPU present or not 
.PP
Definición en la línea 70 del archivo inc/cmsis_43xx_m0app\&.h\&.
.SS "#define __MPU_PRESENT   0"
MPU present or not 
.PP
Definición en la línea 67 del archivo config_43xx_m0app/cmsis_43xx_m0app\&.h\&.
.SS "#define __MPU_PRESENT   0"
MPU present or not 
.PP
Definición en la línea 67 del archivo inc/cmsis_43xx_m0app\&.h\&.
.SS "#define __MPU_PRESENT   0"
MPU present or not 
.PP
Definición en la línea 67 del archivo config_43xx_m0sub/cmsis_43xx_m0sub\&.h\&.
.SS "#define __MPU_PRESENT   0"
MPU present or not 
.PP
Definición en la línea 67 del archivo inc/cmsis_43xx_m0sub\&.h\&.
.SS "#define __NVIC_PRIO_BITS   2"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 68 del archivo config_43xx_m0app/cmsis_43xx_m0app\&.h\&.
.SS "#define __NVIC_PRIO_BITS   2"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 68 del archivo inc/cmsis_43xx_m0app\&.h\&.
.SS "#define __NVIC_PRIO_BITS   2"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 68 del archivo inc/cmsis_43xx_m0sub\&.h\&.
.SS "#define __NVIC_PRIO_BITS   2"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 68 del archivo config_43xx_m0sub/cmsis_43xx_m0sub\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 69 del archivo inc/cmsis_43xx_m0sub\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 69 del archivo inc/cmsis_43xx_m0app\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 69 del archivo config_43xx_m0app/cmsis_43xx_m0app\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 69 del archivo config_43xx_m0sub/cmsis_43xx_m0sub\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
