.TH "CMSIS_glob_defs" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_glob_defs \- CMSIS Global Defines\fBIO Type Qualifiers\fP are used 
.PD 0

.IP "\(bu" 2
to specify the access to peripheral variables\&. 
.IP "\(bu" 2
for automatic generation of peripheral register debug information\&. 
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
