.TH "CMSIS_43XX_COMMON" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_43XX_COMMON \- CHIP: LPC43xx Cortex CMSIS definitions
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fB__CM4_REV\fP   0x0001"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   1"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   3"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   1"
.br
.ti -1c
.RI "#define \fB__CM4_REV\fP   0x0001"
.br
.ti -1c
.RI "#define \fB__MPU_PRESENT\fP   1"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   3"
.br
.ti -1c
.RI "#define \fB__Vendor_SysTickConfig\fP   0"
.br
.ti -1c
.RI "#define \fB__FPU_PRESENT\fP   1"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "#define __CM4_REV   0x0001"
Cortex-M4 Core Revision 
.PP
Definición en la línea 67 del archivo config_43xx/cmsis_43xx\&.h\&.
.SS "#define __CM4_REV   0x0001"
Cortex-M4 Core Revision 
.PP
Definición en la línea 67 del archivo inc/cmsis_43xx\&.h\&.
.SS "#define __FPU_PRESENT   1"
FPU present or not 
.PP
Definición en la línea 71 del archivo config_43xx/cmsis_43xx\&.h\&.
.SS "#define __FPU_PRESENT   1"
FPU present or not 
.PP
Definición en la línea 71 del archivo inc/cmsis_43xx\&.h\&.
.SS "#define __MPU_PRESENT   1"
MPU present or not 
.PP
Definición en la línea 68 del archivo inc/cmsis_43xx\&.h\&.
.SS "#define __MPU_PRESENT   1"
MPU present or not 
.PP
Definición en la línea 68 del archivo config_43xx/cmsis_43xx\&.h\&.
.SS "#define __NVIC_PRIO_BITS   3"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 69 del archivo inc/cmsis_43xx\&.h\&.
.SS "#define __NVIC_PRIO_BITS   3"
Number of Bits used for Priority Levels 
.PP
Definición en la línea 69 del archivo config_43xx/cmsis_43xx\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 70 del archivo config_43xx/cmsis_43xx\&.h\&.
.SS "#define __Vendor_SysTickConfig   0"
Set to 1 if different SysTick Config is used 
.PP
Definición en la línea 70 del archivo inc/cmsis_43xx\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
