.TH "CONTROL_Type" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONTROL_Type \- Union type to access the Control Registers (CONTROL)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm0\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBnPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBSPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBFPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Union type to access the Control Registers (CONTROL)\&. 
.PP
Definición en la línea 257 del archivo core_cm0\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t _reserved0"
bit: 3\&.\&.31 Reserved 
.PP
Definición en la línea 264 del archivo core_cm0\&.h\&.
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   b"
Structure used for bit access 
.SS "uint32_t FPCA"
bit: 2 FP extension active flag 
.PP
Definición en la línea 263 del archivo core_cm0\&.h\&.
.SS "uint32_t nPRIV"
bit: 0 Execution privilege in Thread mode 
.PP
Definición en la línea 261 del archivo core_cm0\&.h\&.
.SS "uint32_t SPSEL"
bit: 1 Stack to be used 
.PP
Definición en la línea 262 del archivo core_cm0\&.h\&.
.SS "uint32_t w"
Type used for word access 
.PP
Definición en la línea 266 del archivo core_cm0\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
