.TH "core_cm4_simd.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_cm4_simd.h \- CMSIS Cortex-M4 SIMD Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fB__CORE_CM4_SIMD_H\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
CMSIS Cortex-M4 SIMD Header File\&. 


.PP
\fBVersión:\fP
.RS 4
V3\&.20 
.RE
.PP
\fBFecha:\fP
.RS 4
25\&. February 2013
.RE
.PP
\fBNota:\fP
.RS 4
.RE
.PP

.PP
Definición en el archivo \fBcore_cm4_simd\&.h\fP\&.
.SH "Documentación de los 'defines'"
.PP 
.SS "#define __CORE_CM4_SIMD_H"

.PP
Definición en la línea 43 del archivo core_cm4_simd\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
