.TH "CREG_18XX_43XX" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CREG_18XX_43XX \- CHIP: LPC18xx/43xx CREG driver
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBLPC_CREG_T\fP"
.br
.RI "\fICREG Register Block\&. \fP"
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBCREG_FLASHTIM_T\fP { \fBFLASHTIM_20MHZ_CPU\fP = 0, \fBFLASHTIM_40MHZ_CPU\fP = 1, \fBFLASHTIM_60MHZ_CPU\fP = 2, \fBFLASHTIM_80MHZ_CPU\fP = 3, \fBFLASHTIM_100MHZ_CPU\fP = 4, \fBFLASHTIM_120MHZ_CPU\fP = 5, \fBFLASHTIM_150MHZ_CPU\fP = 6, \fBFLASHTIM_170MHZ_CPU\fP = 7, \fBFLASHTIM_190MHZ_CPU\fP = 8, \fBFLASHTIM_SAFE_SETTING\fP = 9 }
.RI "\fIFLASH Access time definitions\&. \fP""
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP uint32_t \fBChip_CREG_OnChipFlashIsPresent\fP (void)"
.br
.RI "\fIIdentifies whether on-chip flash is present\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBChip_CREG_SetFlashAcceleration\fP (uint32_t Hz)"
.br
.RI "\fIConfigures the onboard Flash Accelerator in flash-based LPC18xx/LPC43xx parts\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBChip_CREG_SetFLASHAccess\fP (\fBCREG_FLASHTIM_T\fP clks)"
.br
.RI "\fISet FLASH memory access time in clocks\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBChip_CREG_EnableUSB0Phy\fP (void)"
.br
.RI "\fIEnables the USB0 high-speed PHY on LPC18xx/LPC43xx parts\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBChip_CREG_DisableUSB0Phy\fP (void)"
.br
.RI "\fIDisable the USB0 high-speed PHY on LPC18xx/LPC43xx parts\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBChip_CREG_ConfigureBODaR\fP (uint32_t BODVL, uint32_t BORVL)"
.br
.RI "\fIConfigures the BOD and Reset on LPC18xx/LPC43xx parts\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de las enumeraciones"
.PP 
.SS "enum \fBCREG_FLASHTIM_T\fP"

.PP
FLASH Access time definitions\&. 
.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fIFLASHTIM_20MHZ_CPU \fP\fP
Flash accesses use 1 CPU clocks\&. Use for up to 20 MHz CPU clock 
.TP
\fB\fIFLASHTIM_40MHZ_CPU \fP\fP
Flash accesses use 2 CPU clocks\&. Use for up to 40 MHz CPU clock 
.TP
\fB\fIFLASHTIM_60MHZ_CPU \fP\fP
Flash accesses use 3 CPU clocks\&. Use for up to 60 MHz CPU clock 
.TP
\fB\fIFLASHTIM_80MHZ_CPU \fP\fP
Flash accesses use 4 CPU clocks\&. Use for up to 80 MHz CPU clock 
.TP
\fB\fIFLASHTIM_100MHZ_CPU \fP\fP
Flash accesses use 5 CPU clocks\&. Use for up to 100 MHz CPU clock 
.TP
\fB\fIFLASHTIM_120MHZ_CPU \fP\fP
Flash accesses use 6 CPU clocks\&. Use for up to 120 MHz CPU clock 
.TP
\fB\fIFLASHTIM_150MHZ_CPU \fP\fP
Flash accesses use 7 CPU clocks\&. Use for up to 150 Mhz CPU clock 
.TP
\fB\fIFLASHTIM_170MHZ_CPU \fP\fP
Flash accesses use 8 CPU clocks\&. Use for up to 170 MHz CPU clock 
.TP
\fB\fIFLASHTIM_190MHZ_CPU \fP\fP
Flash accesses use 9 CPU clocks\&. Use for up to 190 MHz CPU clock 
.TP
\fB\fIFLASHTIM_SAFE_SETTING \fP\fP
Flash accesses use 10 CPU clocks\&. Safe setting for any allowed conditions 
.PP
Definición en la línea 119 del archivo creg_18xx_43xx\&.h\&.
.SH "Documentación de las funciones"
.PP 
.SS "\fBSTATIC\fP \fBINLINE\fP void Chip_CREG_ConfigureBODaR (uint32_t BODVL, uint32_t BORVL)"

.PP
Configures the BOD and Reset on LPC18xx/LPC43xx parts\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIBODVL\fP : Brown-Out Detect voltage level (0-3) 
.br
\fIBORVL\fP : Brown-Out Reset voltage level (0-3) 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Nothing 
.RE
.PP

.PP
Definición en la línea 176 del archivo creg_18xx_43xx\&.h\&.
.SS "\fBSTATIC\fP \fBINLINE\fP void Chip_CREG_DisableUSB0Phy (void)"

.PP
Disable the USB0 high-speed PHY on LPC18xx/LPC43xx parts\&. 
.PP
\fBDevuelve:\fP
.RS 4
Nothing 
.RE
.PP
\fBNota:\fP
.RS 4
The USB0 PLL & clock should be configured before calling this function\&. This function should be called before the USB0 registers are accessed\&. 
.RE
.PP

.PP
Definición en la línea 165 del archivo creg_18xx_43xx\&.h\&.
.SS "\fBSTATIC\fP \fBINLINE\fP void Chip_CREG_EnableUSB0Phy (void)"

.PP
Enables the USB0 high-speed PHY on LPC18xx/LPC43xx parts\&. 
.PP
\fBDevuelve:\fP
.RS 4
Nothing 
.RE
.PP
\fBNota:\fP
.RS 4
The USB0 PLL & clock should be configured before calling this function\&. This function should be called before the USB0 registers are accessed\&. 
.RE
.PP

.PP
Definición en la línea 154 del archivo creg_18xx_43xx\&.h\&.
.SS "\fBSTATIC\fP \fBINLINE\fP uint32_t Chip_CREG_OnChipFlashIsPresent (void)"

.PP
Identifies whether on-chip flash is present\&. 
.PP
\fBDevuelve:\fP
.RS 4
true if on chip flash is available, otherwise false 
.RE
.PP

.PP
Definición en la línea 95 del archivo creg_18xx_43xx\&.h\&.
.SS "\fBSTATIC\fP \fBINLINE\fP void Chip_CREG_SetFlashAcceleration (uint32_t Hz)"

.PP
Configures the onboard Flash Accelerator in flash-based LPC18xx/LPC43xx parts\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIHz\fP : Current frequency in Hz of the CPU 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Nothing This function should be called with the higher frequency before the clock frequency is increased and it should be called with the new lower value after the clock frequency is decreased\&. 
.RE
.PP

.PP
Definición en la línea 108 del archivo creg_18xx_43xx\&.h\&.
.SS "\fBSTATIC\fP \fBINLINE\fP void Chip_CREG_SetFLASHAccess (\fBCREG_FLASHTIM_T\fP clks)"

.PP
Set FLASH memory access time in clocks\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIclks\fP : FLASH access speed rating 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Nothing 
.RE
.PP

.PP
Definición en la línea 137 del archivo creg_18xx_43xx\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
