.TH "CRSDCEG_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRSDCEG_T \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBminRate\fP"
.br
.ti -1c
.RI "uint8_t \fBcrs\fP"
.br
.ti -1c
.RI "uint8_t \fBdgec\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 39 del archivo hsadc_18xx_43xx\&.c\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t crs"

.PP
Definición en la línea 41 del archivo hsadc_18xx_43xx\&.c\&.
.SS "uint8_t dgec"

.PP
Definición en la línea 42 del archivo hsadc_18xx_43xx\&.c\&.
.SS "uint32_t minRate"

.PP
Definición en la línea 40 del archivo hsadc_18xx_43xx\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
