.TH "dac_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dac_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_DAC_Init\fP (\fBLPC_DAC_T\fP *pDAC)"
.br
.RI "\fIInitial DAC configuration\&. \fP"
.ti -1c
.RI "void \fBChip_DAC_DeInit\fP (\fBLPC_DAC_T\fP *pDAC)"
.br
.RI "\fIShutdown DAC\&. \fP"
.ti -1c
.RI "void \fBChip_DAC_UpdateValue\fP (\fBLPC_DAC_T\fP *pDAC, uint32_t dac_value)"
.br
.RI "\fIUpdate value to DAC buffer\&. \fP"
.ti -1c
.RI "void \fBChip_DAC_SetBias\fP (\fBLPC_DAC_T\fP *pDAC, uint32_t bias)"
.br
.RI "\fISet maximum update rate for DAC\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
