.TH "DMA_ChannelHandle_t" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_ChannelHandle_t \- DMA channel handle structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gpdma_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBFunctionalState\fP \fBChannelStatus\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
DMA channel handle structure\&. 
.PP
Definición en la línea 240 del archivo gpdma_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBFunctionalState\fP ChannelStatus"
DMA channel status 
.PP
Definición en la línea 241 del archivo gpdma_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
