.TH "eeprom.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eeprom.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br
\fC#include 'eeprom\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "uint8_t \fBChip_EEPROM_Write\fP (uint32_t dstAdd, uint8_t *ptr, uint32_t byteswrt)"
.br
.RI "\fIWrite data to EEPROM\&. \fP"
.ti -1c
.RI "uint8_t \fBChip_EEPROM_Read\fP (uint32_t srcAdd, uint8_t *ptr, uint32_t bytesrd)"
.br
.RI "\fIRead data from EEPROM\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
