.TH "ENET_ENHTXDESC_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ENET_ENHTXDESC_T \- Structure of a enhanced transmit descriptor (with timestamp)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enet_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTRLSTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBSIZE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBB1ADD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBB2ADD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDES4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTDES5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTTSL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTTSH\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Structure of a enhanced transmit descriptor (with timestamp) 
.PP
Definición en la línea 416 del archivo enet_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t B1ADD"
Buffer 1 address 
.PP
Definición en la línea 419 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t B2ADD"
Buffer 2 or next descriptor address 
.PP
Definición en la línea 420 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t BSIZE"
Buffer 1/2 byte counts 
.PP
Definición en la línea 418 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t CTRLSTAT"
TDES control and status word 
.PP
Definición en la línea 417 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t TDES4"
Reserved 
.PP
Definición en la línea 421 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t TDES5"
Reserved 
.PP
Definición en la línea 422 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t TTSH"
Timestamp value high 
.PP
Definición en la línea 424 del archivo enet_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t TTSL"
Timestamp value low 
.PP
Definición en la línea 423 del archivo enet_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
