.TH "GIMA_18XX_43XX" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GIMA_18XX_43XX \- CHIP: LPC18xx/43xx GIMA driver
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBLPC_GIMA_T\fP"
.br
.RI "\fIGlobal Input Multiplexer Array (GIMA) register block structure\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
