.TH "gpio_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpio_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_GPIO_Init\fP (\fBLPC_GPIO_T\fP *pGPIO)"
.br
.RI "\fIInitialize GPIO block\&. \fP"
.ti -1c
.RI "void \fBChip_GPIO_DeInit\fP (\fBLPC_GPIO_T\fP *pGPIO)"
.br
.RI "\fIDe-Initialize GPIO block\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
