.TH "groupController" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupController \- Controller Functions
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBPID Motor Control\fP"
.br
.ti -1c
.RI "\fBVector Clarke Transform\fP"
.br
.ti -1c
.RI "\fBVector Inverse Clarke Transform\fP"
.br
.ti -1c
.RI "\fBVector Park Transform\fP"
.br
.ti -1c
.RI "\fBVector Inverse Park transform\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
