.TH "groupInterpolation" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupInterpolation \- Interpolation Functions
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBLinear Interpolation\fP"
.br
.ti -1c
.RI "\fBBilinear Interpolation\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
These functions perform 1- and 2-dimensional interpolation of data\&. Linear interpolation is used for 1-dimensional data and bilinear interpolation is used for 2-dimensional data\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
