.TH "groupCmplxMath" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupCmplxMath \- Complex Math FunctionsThis set of functions operates on complex data vectors\&. The data in the complex arrays is stored in an interleaved fashion (real, imag, real, imag, \&.\&.\&.)\&. In the API functions, the number of samples in a complex array refers to the number of complex values; the array contains twice this number of real values\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
