.TH "i2c_slave_interface" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
i2c_slave_interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBI2C_XFER_T\fP * \fBxfer\fP"
.br
.ti -1c
.RI "\fBI2C_EVENTHANDLER_T\fP \fBevent\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 55 del archivo i2c_18xx_43xx\&.c\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBI2C_EVENTHANDLER_T\fP event"

.PP
Definición en la línea 57 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBI2C_XFER_T\fP* xfer"

.PP
Definición en la línea 56 del archivo i2c_18xx_43xx\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
