.TH "i2c_interface" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
i2c_interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBLPC_I2C_T\fP * \fBip\fP"
.br
.ti -1c
.RI "\fBCHIP_CCU_CLK_T\fP \fBclk\fP"
.br
.ti -1c
.RI "\fBI2C_EVENTHANDLER_T\fP \fBmEvent\fP"
.br
.ti -1c
.RI "\fBI2C_EVENTHANDLER_T\fP \fBsEvent\fP"
.br
.ti -1c
.RI "\fBI2C_XFER_T\fP * \fBmXfer\fP"
.br
.ti -1c
.RI "\fBI2C_XFER_T\fP * \fBsXfer\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 44 del archivo i2c_18xx_43xx\&.c\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBCHIP_CCU_CLK_T\fP clk"

.PP
Definición en la línea 46 del archivo i2c_18xx_43xx\&.c\&.
.SS "uint32_t flags"

.PP
Definición en la línea 51 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBLPC_I2C_T\fP* ip"

.PP
Definición en la línea 45 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBI2C_EVENTHANDLER_T\fP mEvent"

.PP
Definición en la línea 47 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBI2C_XFER_T\fP* mXfer"

.PP
Definición en la línea 49 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBI2C_EVENTHANDLER_T\fP sEvent"

.PP
Definición en la línea 48 del archivo i2c_18xx_43xx\&.c\&.
.SS "\fBI2C_XFER_T\fP* sXfer"

.PP
Definición en la línea 50 del archivo i2c_18xx_43xx\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
