.TH "IP_EMC_STATIC_CONFIG_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IP_EMC_STATIC_CONFIG_T \- EMC Static Configure Structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <emc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBChipSelect\fP"
.br
.ti -1c
.RI "uint32_t \fBConfig\fP"
.br
.ti -1c
.RI "int32_t \fBWaitWen\fP"
.br
.ti -1c
.RI "int32_t \fBWaitOen\fP"
.br
.ti -1c
.RI "int32_t \fBWaitRd\fP"
.br
.ti -1c
.RI "int32_t \fBWaitPage\fP"
.br
.ti -1c
.RI "int32_t \fBWaitWr\fP"
.br
.ti -1c
.RI "int32_t \fBWaitTurn\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
EMC Static Configure Structure\&. 
.PP
Definición en la línea 272 del archivo emc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t ChipSelect"
Chip select 
.PP
Definición en la línea 273 del archivo emc_18xx_43xx\&.h\&.
.SS "uint32_t Config"
Configuration value 
.PP
Definición en la línea 274 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitOen"
Output Enable Wait 
.PP
Definición en la línea 276 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitPage"
Page Access Wait 
.PP
Definición en la línea 278 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitRd"
Read Wait 
.PP
Definición en la línea 277 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitTurn"
Turn around wait 
.PP
Definición en la línea 280 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitWen"
Write Enable Wait 
.PP
Definición en la línea 275 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t WaitWr"
Write Wait 
.PP
Definición en la línea 279 del archivo emc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
