.TH "IP_EMC_DYN_CONFIG_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IP_EMC_DYN_CONFIG_T \- EMC Dynamic Configure Struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <emc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "int32_t \fBRefreshPeriod\fP"
.br
.ti -1c
.RI "uint32_t \fBReadConfig\fP"
.br
.ti -1c
.RI "int32_t \fBtRP\fP"
.br
.ti -1c
.RI "int32_t \fBtRAS\fP"
.br
.ti -1c
.RI "int32_t \fBtSREX\fP"
.br
.ti -1c
.RI "int32_t \fBtAPR\fP"
.br
.ti -1c
.RI "int32_t \fBtDAL\fP"
.br
.ti -1c
.RI "int32_t \fBtWR\fP"
.br
.ti -1c
.RI "int32_t \fBtRC\fP"
.br
.ti -1c
.RI "int32_t \fBtRFC\fP"
.br
.ti -1c
.RI "int32_t \fBtXSR\fP"
.br
.ti -1c
.RI "int32_t \fBtRRD\fP"
.br
.ti -1c
.RI "int32_t \fBtMRD\fP"
.br
.ti -1c
.RI "\fBIP_EMC_DYN_DEVICE_CONFIG_T\fP \fBDevConfig\fP [4]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
EMC Dynamic Configure Struct\&. 
.PP
Definición en la línea 252 del archivo emc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fBIP_EMC_DYN_DEVICE_CONFIG_T\fP DevConfig[4]"
Device Configuration array 
.PP
Definición en la línea 266 del archivo emc_18xx_43xx\&.h\&.
.SS "uint32_t ReadConfig"
Clock 
.PP
Definición en la línea 254 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t RefreshPeriod"
Refresh period 
.PP
Definición en la línea 253 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tAPR"
Last Data Out to Active Time 
.PP
Definición en la línea 258 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tDAL"
Data In to Active Command Time 
.PP
Definición en la línea 259 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tMRD"
Load Mode register command to Active Command 
.PP
Definición en la línea 265 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tRAS"
Active to Precharge Command Period 
.PP
Definición en la línea 256 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tRC"
Active to Active Command Period 
.PP
Definición en la línea 261 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tRFC"
Auto-refresh Period 
.PP
Definición en la línea 262 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tRP"
Precharge Command Period 
.PP
Definición en la línea 255 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tRRD"
Active Bank A to Active Bank B Time 
.PP
Definición en la línea 264 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tSREX"
Self Refresh Exit Time 
.PP
Definición en la línea 257 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tWR"
Write Recovery Time 
.PP
Definición en la línea 260 del archivo emc_18xx_43xx\&.h\&.
.SS "int32_t tXSR"
Exit Selt Refresh 
.PP
Definición en la línea 263 del archivo emc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
