.TH "IP_EMC_DYN_DEVICE_CONFIG_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IP_EMC_DYN_DEVICE_CONFIG_T \- EMC Dynamic Device Configuration structure used for IP drivers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <emc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBBaseAddr\fP"
.br
.ti -1c
.RI "uint8_t \fBRAS\fP"
.br
.ti -1c
.RI "uint32_t \fBModeRegister\fP"
.br
.ti -1c
.RI "uint32_t \fBDynConfig\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
EMC Dynamic Device Configuration structure used for IP drivers\&. 
.PP
Definición en la línea 242 del archivo emc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t BaseAddr"
Base Address 
.PP
Definición en la línea 243 del archivo emc_18xx_43xx\&.h\&.
.SS "uint32_t DynConfig"
Dynamic Configuration value 
.PP
Definición en la línea 246 del archivo emc_18xx_43xx\&.h\&.
.SS "uint32_t ModeRegister"
Mode Register value 
.PP
Definición en la línea 245 del archivo emc_18xx_43xx\&.h\&.
.SS "uint8_t RAS"
RAS value 
.PP
Definición en la línea 244 del archivo emc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
