.TH "LCD_PALETTE_ENTRY_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LCD_PALETTE_ENTRY_T \- LCD Palette entry format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lcd_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBRl\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBGl\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBBl\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBIl\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBRu\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBGu\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBBu\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBIu\fP: 1"
.br
.in -1c
.SH "Descripción detallada"
.PP 
LCD Palette entry format\&. 
.PP
Definición en la línea 81 del archivo lcd_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t Bl"

.PP
Definición en la línea 84 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Bu"

.PP
Definición en la línea 88 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Gl"

.PP
Definición en la línea 83 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Gu"

.PP
Definición en la línea 87 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Il"

.PP
Definición en la línea 85 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Iu"

.PP
Definición en la línea 89 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Rl"

.PP
Definición en la línea 82 del archivo lcd_18xx_43xx\&.h\&.
.SS "uint32_t Ru"

.PP
Definición en la línea 86 del archivo lcd_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
