.TH "LPC_OTP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPC_OTP_T \- OTP Register block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <otp_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP0_0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP0_1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP0_2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP0_3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP1_0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP1_1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP1_2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP1_3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP2_0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP2_1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP2_2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP2_3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP3_0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP3_1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP3_2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOTP3_3\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
OTP Register block\&. 
.PP
Definición en la línea 47 del archivo otp_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t OTP0_0"
(@ 0x40045000) OTP content 
.PP
Definición en la línea 48 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP0_1"
(@ 0x40045004) OTP content 
.PP
Definición en la línea 49 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP0_2"
(@ 0x40045008) OTP content 
.PP
Definición en la línea 50 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP0_3"
(@ 0x4004500C) OTP content 
.PP
Definición en la línea 51 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP1_0"
(@ 0x40045010) OTP content 
.PP
Definición en la línea 52 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP1_1"
(@ 0x40045014) OTP content 
.PP
Definición en la línea 53 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP1_2"
(@ 0x40045018) OTP content 
.PP
Definición en la línea 54 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP1_3"
(@ 0x4004501C) OTP content 
.PP
Definición en la línea 55 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP2_0"
(@ 0x40045020) OTP content 
.PP
Definición en la línea 56 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP2_1"
(@ 0x40045024) OTP content 
.PP
Definición en la línea 57 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP2_2"
(@ 0x40045028) OTP content 
.PP
Definición en la línea 58 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP2_3"
(@ 0x4004502C) OTP content 
.PP
Definición en la línea 59 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP3_0"
(@ 0x40045030) OTP content 
.PP
Definición en la línea 60 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP3_1"
(@ 0x40045034) OTP content 
.PP
Definición en la línea 61 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP3_2"
(@ 0x40045038) OTP content 
.PP
Definición en la línea 62 del archivo otp_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t OTP3_3"
(@ 0x4004503C) OTP content 
.PP
Definición en la línea 63 del archivo otp_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
