.TH "LPC_REGFILE_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPC_REGFILE_T \- Register File register block structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBREGFILE\fP [64]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Register File register block structure\&. 
.PP
Definición en la línea 101 del archivo rtc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t REGFILE[64]"
General purpose storage register 
.PP
Definición en la línea 102 del archivo rtc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
