.TH "LPC_PIN_INT_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPC_PIN_INT_T \- LPC18xx/43xx Pin Interrupt and Pattern Match register block structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pinint_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISEL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSIENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCIENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIENF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSIENF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCIENF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRISE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFALL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIST\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
LPC18xx/43xx Pin Interrupt and Pattern Match register block structure\&. 
.PP
Definición en la línea 47 del archivo pinint_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t CIENF"
Clear Pin Interrupt Enable Falling Edge / Active Level address 
.PP
Definición en la línea 54 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t CIENR"
Clear Pin Interrupt Enable (Rising) register 
.PP
Definición en la línea 51 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t FALL"
Pin Interrupt Falling Edge register 
.PP
Definición en la línea 56 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t IENF"
Pin Interrupt Enable Falling Edge / Active Level register 
.PP
Definición en la línea 52 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t IENR"
Pin Interrupt Enable (Rising) register 
.PP
Definición en la línea 49 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t ISEL"
< PIN_INT Structure Pin Interrupt Mode register 
.PP
Definición en la línea 48 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t IST"
Pin Interrupt Status register 
.PP
Definición en la línea 57 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t RISE"
Pin Interrupt Rising Edge register 
.PP
Definición en la línea 55 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t SIENF"
Set Pin Interrupt Enable Falling Edge / Active Level register 
.PP
Definición en la línea 53 del archivo pinint_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t SIENR"
Set Pin Interrupt Enable (Rising) register 
.PP
Definición en la línea 50 del archivo pinint_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
