.TH "LPC_FMC_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPC_FMC_T \- FLASH Memory Controller Unit register block structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fmc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP [8]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFMSSTART\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFMSSTOP\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFMSW\fP [4]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED3\fP [1001]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFMSTAT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBFMSTATCLR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED4\fP [5]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
FLASH Memory Controller Unit register block structure\&. 
.PP
Definición en la línea 47 del archivo fmc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t FMSSTART"

.PP
Definición en la línea 49 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t FMSSTOP"

.PP
Definición en la línea 50 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t FMSTAT"

.PP
Definición en la línea 54 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__O\fP uint32_t FMSTATCLR"

.PP
Definición en la línea 56 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t FMSW[4]"

.PP
Definición en la línea 52 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED1[8]"
< FMC Structure 
.PP
Definición en la línea 48 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED2"

.PP
Definición en la línea 51 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED3[1001]"

.PP
Definición en la línea 53 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED4[5]"

.PP
Definición en la línea 57 del archivo fmc_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t RESERVED5"

.PP
Definición en la línea 55 del archivo fmc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
