.TH "LPC_I2C_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPC_I2C_T \- I2C register block structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2c_common_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCONSET\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBSTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADR0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCLH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCLL\fP"
.br
.ti -1c
.RI "\fB__O\fP uint32_t \fBCONCLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMMCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADR3\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBDATA_BUFFER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK\fP [4]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
I2C register block structure\&. 
.PP
Definición en la línea 47 del archivo i2c_common_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "\fB__IO\fP uint32_t ADR0"
I2C Slave Address Register 0\&. Contains the 7-bit slave address for operation of the I2C interface in slave mode, and is not used in master mode\&. The least significant bit determines whether a slave responds to the General Call address\&. 
.PP
Definición en la línea 51 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t ADR1"
I2C Slave Address Register\&. Contains the 7-bit slave address for operation of the I2C interface in slave mode, and is not used in master mode\&. The least significant bit determines whether a slave responds to the General Call address\&. 
.PP
Definición en la línea 56 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t ADR2"
I2C Slave Address Register\&. Contains the 7-bit slave address for operation of the I2C interface in slave mode, and is not used in master mode\&. The least significant bit determines whether a slave responds to the General Call address\&. 
.PP
Definición en la línea 57 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t ADR3"
I2C Slave Address Register\&. Contains the 7-bit slave address for operation of the I2C interface in slave mode, and is not used in master mode\&. The least significant bit determines whether a slave responds to the General Call address\&. 
.PP
Definición en la línea 58 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__O\fP uint32_t CONCLR"
I2C Control Clear Register\&. When a one is written to a bit of this register, the corresponding bit in the I2C control register is cleared\&. Writing a zero has no effect on the corresponding bit in the I2C control register\&. 
.PP
Definición en la línea 54 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t CONSET"
I2C Control Set Register\&. When a one is written to a bit of this register, the corresponding bit in the I2C control register is set\&. Writing a zero has no effect on the corresponding bit in the I2C control register\&. 
.PP
Definición en la línea 48 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t DAT"
I2C Data Register\&. During master or slave transmit mode, data to be transmitted is written to this register\&. During master or slave receive mode, data that has been received may be read from this register\&. 
.PP
Definición en la línea 50 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t DATA_BUFFER"
Data buffer register\&. The contents of the 8 MSBs of the DAT shift register will be transferred to the DATA_BUFFER automatically after every nine bits (8 bits of data plus ACK or NACK) has been received on the bus\&. 
.PP
Definición en la línea 59 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t MASK[4]"
I2C Slave address mask register 
.PP
Definición en la línea 60 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t MMCTRL"
Monitor mode control register\&. 
.PP
Definición en la línea 55 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t SCLH"
SCH Duty Cycle Register High Half Word\&. Determines the high time of the I2C clock\&. 
.PP
Definición en la línea 52 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__IO\fP uint32_t SCLL"
SCL Duty Cycle Register Low Half Word\&. Determines the low time of the I2C clock\&. SCLL and SCLH together determine the clock frequency generated by an I2C master and certain times used in slave mode\&. 
.PP
Definición en la línea 53 del archivo i2c_common_18xx_43xx\&.h\&.
.SS "\fB__I\fP uint32_t STAT"
I2C Status Register\&. During I2C operation, this register provides detailed status codes that allow software to determine the next action needed\&. 
.PP
Definición en la línea 49 del archivo i2c_common_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
