.TH "LPCSPIFILIB_HW_L2" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPCSPIFILIB_HW_L2 \- LPCSPIFILIB hardware support API functions
.SH "Descripción detallada"
.PP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
