.TH "LPCSPIFILIB_HW_API" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LPCSPIFILIB_HW_API \- LPCSPIFILIB hardware definitions and API functions
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBLPCSPIFILIB primative API functions\fP"
.br
.ti -1c
.RI "\fBLPCSPIFILIB hardware support API functions\fP"
.br
.in -1c
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBLPC_SPIFI_CHIPHW\fP"
.br
.RI "\fISPIFI controller hardware register structure\&. \fP"
.in -1c
.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef struct \fBLPC_SPIFI_CHIPHW\fP \fBLPC_SPIFI_T\fP"
.br
.RI "\fISPIFI controller hardware register structure\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef struct \fBLPC_SPIFI_CHIPHW\fP  \fBLPC_SPIFI_T\fP"

.PP
SPIFI controller hardware register structure\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
