.TH "sys_config.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sys_config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBCHIP_LPC43XX\fP"
.br
.ti -1c
.RI "#define \fBLPC43XX_CORE_M0APP\fP"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define CHIP_LPC43XX"

.PP
Definición en la línea 34 del archivo m0app/sys_config\&.h\&.
.SS "#define LPC43XX_CORE_M0APP"

.PP
Definición en la línea 37 del archivo m0app/sys_config\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
