.TH "OTP_18XX_43XX" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OTP_18XX_43XX \- CHIP: LPC18xx/43xx OTP Controller driver
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBLPC_OTP_T\fP"
.br
.RI "\fIOTP Register block\&. \fP"
.in -1c
.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef enum \fBCHIP_OTP_BOOT_SRC\fP \fBCHIP_OTP_BOOT_SRC_T\fP"
.br
.RI "\fIOTP Boot Source selection used in Chip driver\&. \fP"
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBCHIP_OTP_BOOT_SRC\fP { \fBCHIP_OTP_BOOTSRC_PINS\fP, \fBCHIP_OTP_BOOTSRC_UART0\fP, \fBCHIP_OTP_BOOTSRC_SPIFI\fP, \fBCHIP_OTP_BOOTSRC_EMC8\fP, \fBCHIP_OTP_BOOTSRC_EMC16\fP, \fBCHIP_OTP_BOOTSRC_EMC32\fP, \fBCHIP_OTP_BOOTSRC_USB0\fP, \fBCHIP_OTP_BOOTSRC_USB1\fP, \fBCHIP_OTP_BOOTSRC_SPI\fP, \fBCHIP_OTP_BOOTSRC_UART3\fP }
.RI "\fIOTP Boot Source selection used in Chip driver\&. \fP""
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "uint32_t \fBChip_OTP_Init\fP (void)"
.br
.RI "\fIInitialize for OTP Controller functions\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_ProgBootSrc\fP (\fBCHIP_OTP_BOOT_SRC_T\fP BootSrc)"
.br
.RI "\fIProgram boot source in OTP Controller\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_ProgJTAGDis\fP (void)"
.br
.RI "\fIProgram the JTAG bit in OTP Controller\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_ProgUSBID\fP (uint32_t ProductID, uint32_t VendorID)"
.br
.RI "\fIProgram USB ID in OTP Controller\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_ProgGPWord\fP (uint32_t WordNum, uint32_t Data, uint32_t Mask)"
.br
.RI "\fIProgram OTP GP Word memory\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_ProgKey\fP (uint32_t KeyNum, uint8_t *key)"
.br
.RI "\fIProgram AES Key\&. \fP"
.ti -1c
.RI "uint32_t \fBChip_OTP_GenRand\fP (void)"
.br
.RI "\fIGenerate Random Number using HW Random Number Generator\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef enum \fBCHIP_OTP_BOOT_SRC\fP  \fBCHIP_OTP_BOOT_SRC_T\fP"

.PP
OTP Boot Source selection used in Chip driver\&. 
.SH "Documentación de las enumeraciones"
.PP 
.SS "enum \fBCHIP_OTP_BOOT_SRC\fP"

.PP
OTP Boot Source selection used in Chip driver\&. 
.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fICHIP_OTP_BOOTSRC_PINS \fP\fP
Boot source - External pins 
.TP
\fB\fICHIP_OTP_BOOTSRC_UART0 \fP\fP
Boot source - UART0 
.TP
\fB\fICHIP_OTP_BOOTSRC_SPIFI \fP\fP
Boot source - EMC 8-bit memory 
.TP
\fB\fICHIP_OTP_BOOTSRC_EMC8 \fP\fP
Boot source - EMC 16-bit memory 
.TP
\fB\fICHIP_OTP_BOOTSRC_EMC16 \fP\fP
Boot source - EMC 32-bit memory 
.TP
\fB\fICHIP_OTP_BOOTSRC_EMC32 \fP\fP
Boot source - EMC 32-bit memory 
.TP
\fB\fICHIP_OTP_BOOTSRC_USB0 \fP\fP
Boot source - DFU USB0 boot 
.TP
\fB\fICHIP_OTP_BOOTSRC_USB1 \fP\fP
Boot source - DFU USB1 boot 
.TP
\fB\fICHIP_OTP_BOOTSRC_SPI \fP\fP
Boot source - SPI boot 
.TP
\fB\fICHIP_OTP_BOOTSRC_UART3 \fP\fP
Boot source - UART3 
.PP
Definición en la línea 69 del archivo otp_18xx_43xx\&.h\&.
.SH "Documentación de las funciones"
.PP 
.SS "uint32_t Chip_OTP_GenRand (void)"

.PP
Generate Random Number using HW Random Number Generator\&. 
.PP
\fBDevuelve:\fP
.RS 4
Error code of the random number generation\&. To load the random number into AES, call Chip_AES_LoadKeyRNG 
.RE
.PP

.PP
Definición en la línea 142 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_Init (void)"

.PP
Initialize for OTP Controller functions\&. 
.PP
\fBDevuelve:\fP
.RS 4
Status of Otp_Init function This function will initialise all the OTP driver function pointers and call the ROM OTP Initialisation function\&. 
.RE
.PP

.PP
Definición en la línea 66 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_ProgBootSrc (\fBCHIP_OTP_BOOT_SRC_T\fP BootSrc)"

.PP
Program boot source in OTP Controller\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIBootSrc\fP : Boot Source enum value 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Status 
.RE
.PP

.PP
Definición en la línea 87 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_ProgGPWord (uint32_t WordNum, uint32_t Data, uint32_t Mask)"

.PP
Program OTP GP Word memory\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIWordNum\fP : Word Number (Select word 0 or word 1 or word 2) 
.br
\fIData\fP : Data value 
.br
\fIMask\fP : Mask value 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Status This function available in devices which are not AES capable 
.RE
.PP

.PP
Definición en la línea 105 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_ProgJTAGDis (void)"

.PP
Program the JTAG bit in OTP Controller\&. 
.PP
\fBDevuelve:\fP
.RS 4
Status 
.RE
.PP

.PP
Definición en la línea 93 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_ProgKey (uint32_t KeyNum, uint8_t * key)"

.PP
Program AES Key\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIKeyNum\fP : Key Number (Select 0 or 1) 
.br
\fIkey\fP : Pointer to AES Key (16 bytes required) 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Status This function available in devices which are AES capable 
.RE
.PP

.PP
Definición en la línea 128 del archivo otp_18xx_43xx\&.c\&.
.SS "uint32_t Chip_OTP_ProgUSBID (uint32_t ProductID, uint32_t VendorID)"

.PP
Program USB ID in OTP Controller\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIProductID\fP : USB Product ID 
.br
\fIVendorID\fP : USB Vendor ID 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Status 
.RE
.PP

.PP
Definición en la línea 99 del archivo otp_18xx_43xx\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
