.TH "packing.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packing.h \- 
.SH SYNOPSIS
.br
.PP
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBPRE_PACK\fP   /* Nothing */"
.br
.ti -1c
.RI "#define \fBPOST_PACK\fP   /* Nothing */"
.br
.ti -1c
.RI "#define \fBALIGNED\fP(n)   /* Nothing */"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define ALIGNED(n)   /* Nothing */"

.PP
Definición en la línea 37 del archivo packing\&.h\&.
.SS "#define POST_PACK   /* Nothing */"

.PP
Definición en la línea 36 del archivo packing\&.h\&.
.SS "#define PRE_PACK   /* Nothing */"

.PP
Definición en la línea 35 del archivo packing\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
