.TH "PERIPH_18XX_BASE" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PERIPH_18XX_BASE \- CHIP: LPC18xx Peripheral addresses and register set declarations
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBLPC_SCT_BASE\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBLPC_GPDMA_BASE\fP   0x40002000"
.br
.ti -1c
.RI "#define \fBLPC_SPIFI_BASE\fP   0x40003000"
.br
.ti -1c
.RI "#define \fBLPC_SDMMC_BASE\fP   0x40004000"
.br
.ti -1c
.RI "#define \fBLPC_EMC_BASE\fP   0x40005000"
.br
.ti -1c
.RI "#define \fBLPC_USB0_BASE\fP   0x40006000"
.br
.ti -1c
.RI "#define \fBLPC_USB1_BASE\fP   0x40007000"
.br
.ti -1c
.RI "#define \fBLPC_LCD_BASE\fP   0x40008000"
.br
.ti -1c
.RI "#define \fBLPC_FMCA_BASE\fP   0x4000C000"
.br
.ti -1c
.RI "#define \fBLPC_FMCB_BASE\fP   0x4000D000"
.br
.ti -1c
.RI "#define \fBLPC_ETHERNET_BASE\fP   0x40010000"
.br
.ti -1c
.RI "#define \fBLPC_ATIMER_BASE\fP   0x40040000"
.br
.ti -1c
.RI "#define \fBLPC_REGFILE_BASE\fP   0x40041000"
.br
.ti -1c
.RI "#define \fBLPC_PMC_BASE\fP   0x40042000"
.br
.ti -1c
.RI "#define \fBLPC_CREG_BASE\fP   0x40043000"
.br
.ti -1c
.RI "#define \fBLPC_EVRT_BASE\fP   0x40044000"
.br
.ti -1c
.RI "#define \fBLPC_OTP_BASE\fP   0x40045000"
.br
.ti -1c
.RI "#define \fBLPC_RTC_BASE\fP   0x40046000"
.br
.ti -1c
.RI "#define \fBLPC_CGU_BASE\fP   0x40050000"
.br
.ti -1c
.RI "#define \fBLPC_CCU1_BASE\fP   0x40051000"
.br
.ti -1c
.RI "#define \fBLPC_CCU2_BASE\fP   0x40052000"
.br
.ti -1c
.RI "#define \fBLPC_RGU_BASE\fP   0x40053000"
.br
.ti -1c
.RI "#define \fBLPC_WWDT_BASE\fP   0x40080000"
.br
.ti -1c
.RI "#define \fBLPC_USART0_BASE\fP   0x40081000"
.br
.ti -1c
.RI "#define \fBLPC_USART2_BASE\fP   0x400C1000"
.br
.ti -1c
.RI "#define \fBLPC_USART3_BASE\fP   0x400C2000"
.br
.ti -1c
.RI "#define \fBLPC_UART1_BASE\fP   0x40082000"
.br
.ti -1c
.RI "#define \fBLPC_SSP0_BASE\fP   0x40083000"
.br
.ti -1c
.RI "#define \fBLPC_SSP1_BASE\fP   0x400C5000"
.br
.ti -1c
.RI "#define \fBLPC_TIMER0_BASE\fP   0x40084000"
.br
.ti -1c
.RI "#define \fBLPC_TIMER1_BASE\fP   0x40085000"
.br
.ti -1c
.RI "#define \fBLPC_TIMER2_BASE\fP   0x400C3000"
.br
.ti -1c
.RI "#define \fBLPC_TIMER3_BASE\fP   0x400C4000"
.br
.ti -1c
.RI "#define \fBLPC_SCU_BASE\fP   0x40086000"
.br
.ti -1c
.RI "#define \fBLPC_PIN_INT_BASE\fP   0x40087000"
.br
.ti -1c
.RI "#define \fBLPC_GPIO_GROUP_INT0_BASE\fP   0x40088000"
.br
.ti -1c
.RI "#define \fBLPC_GPIO_GROUP_INT1_BASE\fP   0x40089000"
.br
.ti -1c
.RI "#define \fBLPC_MCPWM_BASE\fP   0x400A0000"
.br
.ti -1c
.RI "#define \fBLPC_I2C0_BASE\fP   0x400A1000"
.br
.ti -1c
.RI "#define \fBLPC_I2C1_BASE\fP   0x400E0000"
.br
.ti -1c
.RI "#define \fBLPC_I2S0_BASE\fP   0x400A2000"
.br
.ti -1c
.RI "#define \fBLPC_I2S1_BASE\fP   0x400A3000"
.br
.ti -1c
.RI "#define \fBLPC_C_CAN1_BASE\fP   0x400A4000"
.br
.ti -1c
.RI "#define \fBLPC_RITIMER_BASE\fP   0x400C0000"
.br
.ti -1c
.RI "#define \fBLPC_QEI_BASE\fP   0x400C6000"
.br
.ti -1c
.RI "#define \fBLPC_GIMA_BASE\fP   0x400C7000"
.br
.ti -1c
.RI "#define \fBLPC_DAC_BASE\fP   0x400E1000"
.br
.ti -1c
.RI "#define \fBLPC_C_CAN0_BASE\fP   0x400E2000"
.br
.ti -1c
.RI "#define \fBLPC_ADC0_BASE\fP   0x400E3000"
.br
.ti -1c
.RI "#define \fBLPC_ADC1_BASE\fP   0x400E4000"
.br
.ti -1c
.RI "#define \fBLPC_GPIO_PORT_BASE\fP   0x400F4000"
.br
.ti -1c
.RI "#define \fBLPC_SPI_BASE\fP   0x40100000"
.br
.ti -1c
.RI "#define \fBLPC_SGPIO_BASE\fP   0x40101000"
.br
.ti -1c
.RI "#define \fBLPC_EEPROM_BASE\fP   0x4000E000"
.br
.ti -1c
.RI "#define \fBLPC_ROM_API_BASE\fP   0x10400100"
.br
.ti -1c
.RI "#define \fBLPC_SCT\fP   ((\fBLPC_SCT_T\fP              *) \fBLPC_SCT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_GPDMA\fP   ((\fBLPC_GPDMA_T\fP            *) \fBLPC_GPDMA_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_SPIFI\fP   ((\fBLPC_SPIFI_T\fP            *) \fBLPC_SPIFI_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_SDMMC\fP   ((\fBLPC_SDMMC_T\fP            *) \fBLPC_SDMMC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_EMC\fP   ((\fBLPC_EMC_T\fP              *) \fBLPC_EMC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_USB0\fP   ((\fBLPC_USBHS_T\fP            *) \fBLPC_USB0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_USB1\fP   ((\fBLPC_USBHS_T\fP            *) \fBLPC_USB1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_LCD\fP   ((\fBLPC_LCD_T\fP              *) \fBLPC_LCD_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_ETHERNET\fP   ((\fBLPC_ENET_T\fP             *) \fBLPC_ETHERNET_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_ATIMER\fP   ((\fBLPC_ATIMER_T\fP           *) \fBLPC_ATIMER_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_REGFILE\fP   ((\fBLPC_REGFILE_T\fP          *) \fBLPC_REGFILE_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_PMC\fP   ((\fBLPC_PMC_T\fP              *) \fBLPC_PMC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_EVRT\fP   ((\fBLPC_EVRT_T\fP             *) \fBLPC_EVRT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_RTC\fP   ((\fBLPC_RTC_T\fP              *) \fBLPC_RTC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_CGU\fP   ((\fBLPC_CGU_T\fP              *) \fBLPC_CGU_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_CCU1\fP   ((\fBLPC_CCU1_T\fP             *) \fBLPC_CCU1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_CCU2\fP   ((\fBLPC_CCU2_T\fP             *) \fBLPC_CCU2_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_CREG\fP   ((\fBLPC_CREG_T\fP             *) \fBLPC_CREG_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_RGU\fP   ((\fBLPC_RGU_T\fP              *) \fBLPC_RGU_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_WWDT\fP   ((\fBLPC_WWDT_T\fP             *) \fBLPC_WWDT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_USART0\fP   ((\fBLPC_USART_T\fP            *) \fBLPC_USART0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_USART2\fP   ((\fBLPC_USART_T\fP            *) \fBLPC_USART2_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_USART3\fP   ((\fBLPC_USART_T\fP            *) \fBLPC_USART3_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_UART1\fP   ((\fBLPC_USART_T\fP            *) \fBLPC_UART1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_SSP0\fP   ((\fBLPC_SSP_T\fP              *) \fBLPC_SSP0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_SSP1\fP   ((\fBLPC_SSP_T\fP              *) \fBLPC_SSP1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_TIMER0\fP   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_TIMER1\fP   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_TIMER2\fP   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER2_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_TIMER3\fP   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER3_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_SCU\fP   ((\fBLPC_SCU_T\fP              *) \fBLPC_SCU_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_GPIO_PIN_INT\fP   ((\fBLPC_PIN_INT_T\fP          *) \fBLPC_PIN_INT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_GPIOGROUP\fP   ((\fBLPC_GPIOGROUPINT_T\fP     *) \fBLPC_GPIO_GROUP_INT0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_MCPWM\fP   ((\fBLPC_MCPWM_T\fP            *) \fBLPC_MCPWM_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_I2C0\fP   ((\fBLPC_I2C_T\fP              *) \fBLPC_I2C0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_I2C1\fP   ((\fBLPC_I2C_T\fP              *) \fBLPC_I2C1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_I2S0\fP   ((\fBLPC_I2S_T\fP              *) \fBLPC_I2S0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_I2S1\fP   ((\fBLPC_I2S_T\fP              *) \fBLPC_I2S1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_C_CAN1\fP   ((\fBLPC_CCAN_T\fP             *) \fBLPC_C_CAN1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_RITIMER\fP   ((\fBLPC_RITIMER_T\fP          *) \fBLPC_RITIMER_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_QEI\fP   ((\fBLPC_QEI_T\fP              *) \fBLPC_QEI_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_GIMA\fP   ((\fBLPC_GIMA_T\fP             *) \fBLPC_GIMA_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_DAC\fP   ((\fBLPC_DAC_T\fP              *) \fBLPC_DAC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_C_CAN0\fP   ((\fBLPC_CCAN_T\fP             *) \fBLPC_C_CAN0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_ADC0\fP   ((\fBLPC_ADC_T\fP              *) \fBLPC_ADC0_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_ADC1\fP   ((\fBLPC_ADC_T\fP              *) \fBLPC_ADC1_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_GPIO_PORT\fP   ((\fBLPC_GPIO_T\fP             *) \fBLPC_GPIO_PORT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_EEPROM\fP   ((\fBLPC_EEPROM_T\fP           *) \fBLPC_EEPROM_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_FMCA\fP   ((\fBLPC_FMC_T\fP              *) \fBLPC_FMCA_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_FMCB\fP   ((\fBLPC_FMC_T\fP              *) \fBLPC_FMCB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBLPC_ROM_API\fP   ((\fBLPC_ROM_API_T\fP          *) \fBLPC_ROM_API_BASE\fP)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "#define LPC_ADC0   ((\fBLPC_ADC_T\fP              *) \fBLPC_ADC0_BASE\fP)"

.PP
Definición en la línea 154 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ADC0_BASE   0x400E3000"

.PP
Definición en la línea 102 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ADC1   ((\fBLPC_ADC_T\fP              *) \fBLPC_ADC1_BASE\fP)"

.PP
Definición en la línea 155 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ADC1_BASE   0x400E4000"

.PP
Definición en la línea 103 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ATIMER   ((\fBLPC_ATIMER_T\fP           *) \fBLPC_ATIMER_BASE\fP)"

.PP
Definición en la línea 119 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ATIMER_BASE   0x40040000"

.PP
Definición en la línea 65 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_C_CAN0   ((\fBLPC_CCAN_T\fP             *) \fBLPC_C_CAN0_BASE\fP)"

.PP
Definición en la línea 153 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_C_CAN0_BASE   0x400E2000"

.PP
Definición en la línea 101 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_C_CAN1   ((\fBLPC_CCAN_T\fP             *) \fBLPC_C_CAN1_BASE\fP)"

.PP
Definición en la línea 148 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_C_CAN1_BASE   0x400A4000"

.PP
Definición en la línea 96 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CCU1   ((\fBLPC_CCU1_T\fP             *) \fBLPC_CCU1_BASE\fP)"

.PP
Definición en la línea 125 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CCU1_BASE   0x40051000"

.PP
Definición en la línea 73 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CCU2   ((\fBLPC_CCU2_T\fP             *) \fBLPC_CCU2_BASE\fP)"

.PP
Definición en la línea 126 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CCU2_BASE   0x40052000"

.PP
Definición en la línea 74 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CGU   ((\fBLPC_CGU_T\fP              *) \fBLPC_CGU_BASE\fP)"

.PP
Definición en la línea 124 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CGU_BASE   0x40050000"

.PP
Definición en la línea 72 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CREG   ((\fBLPC_CREG_T\fP             *) \fBLPC_CREG_BASE\fP)"

.PP
Definición en la línea 127 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_CREG_BASE   0x40043000"

.PP
Definición en la línea 68 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_DAC   ((\fBLPC_DAC_T\fP              *) \fBLPC_DAC_BASE\fP)"

.PP
Definición en la línea 152 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_DAC_BASE   0x400E1000"

.PP
Definición en la línea 100 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EEPROM   ((\fBLPC_EEPROM_T\fP           *) \fBLPC_EEPROM_BASE\fP)"

.PP
Definición en la línea 157 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EEPROM_BASE   0x4000E000"

.PP
Definición en la línea 107 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EMC   ((\fBLPC_EMC_T\fP              *) \fBLPC_EMC_BASE\fP)"

.PP
Definición en la línea 114 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EMC_BASE   0x40005000"

.PP
Definición en la línea 58 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ETHERNET   ((\fBLPC_ENET_T\fP             *) \fBLPC_ETHERNET_BASE\fP)"

.PP
Definición en la línea 118 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ETHERNET_BASE   0x40010000"

.PP
Definición en la línea 64 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EVRT   ((\fBLPC_EVRT_T\fP             *) \fBLPC_EVRT_BASE\fP)"

.PP
Definición en la línea 122 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_EVRT_BASE   0x40044000"

.PP
Definición en la línea 69 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_FMCA   ((\fBLPC_FMC_T\fP              *) \fBLPC_FMCA_BASE\fP)"

.PP
Definición en la línea 158 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_FMCA_BASE   0x4000C000"

.PP
Definición en la línea 62 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_FMCB   ((\fBLPC_FMC_T\fP              *) \fBLPC_FMCB_BASE\fP)"

.PP
Definición en la línea 159 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_FMCB_BASE   0x4000D000"

.PP
Definición en la línea 63 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GIMA   ((\fBLPC_GIMA_T\fP             *) \fBLPC_GIMA_BASE\fP)"

.PP
Definición en la línea 151 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GIMA_BASE   0x400C7000"

.PP
Definición en la línea 99 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPDMA   ((\fBLPC_GPDMA_T\fP            *) \fBLPC_GPDMA_BASE\fP)"

.PP
Definición en la línea 111 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPDMA_BASE   0x40002000"

.PP
Definición en la línea 55 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIO_GROUP_INT0_BASE   0x40088000"

.PP
Definición en la línea 89 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIO_GROUP_INT1_BASE   0x40089000"

.PP
Definición en la línea 90 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIO_PIN_INT   ((\fBLPC_PIN_INT_T\fP          *) \fBLPC_PIN_INT_BASE\fP)"

.PP
Definición en la línea 141 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIO_PORT   ((\fBLPC_GPIO_T\fP             *) \fBLPC_GPIO_PORT_BASE\fP)"

.PP
Definición en la línea 156 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIO_PORT_BASE   0x400F4000"

.PP
Definición en la línea 104 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_GPIOGROUP   ((\fBLPC_GPIOGROUPINT_T\fP     *) \fBLPC_GPIO_GROUP_INT0_BASE\fP)"

.PP
Definición en la línea 142 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2C0   ((\fBLPC_I2C_T\fP              *) \fBLPC_I2C0_BASE\fP)"

.PP
Definición en la línea 144 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2C0_BASE   0x400A1000"

.PP
Definición en la línea 92 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2C1   ((\fBLPC_I2C_T\fP              *) \fBLPC_I2C1_BASE\fP)"

.PP
Definición en la línea 145 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2C1_BASE   0x400E0000"

.PP
Definición en la línea 93 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2S0   ((\fBLPC_I2S_T\fP              *) \fBLPC_I2S0_BASE\fP)"

.PP
Definición en la línea 146 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2S0_BASE   0x400A2000"

.PP
Definición en la línea 94 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2S1   ((\fBLPC_I2S_T\fP              *) \fBLPC_I2S1_BASE\fP)"

.PP
Definición en la línea 147 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_I2S1_BASE   0x400A3000"

.PP
Definición en la línea 95 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_LCD   ((\fBLPC_LCD_T\fP              *) \fBLPC_LCD_BASE\fP)"

.PP
Definición en la línea 117 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_LCD_BASE   0x40008000"

.PP
Definición en la línea 61 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_MCPWM   ((\fBLPC_MCPWM_T\fP            *) \fBLPC_MCPWM_BASE\fP)"

.PP
Definición en la línea 143 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_MCPWM_BASE   0x400A0000"

.PP
Definición en la línea 91 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_OTP_BASE   0x40045000"

.PP
Definición en la línea 70 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_PIN_INT_BASE   0x40087000"

.PP
Definición en la línea 88 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_PMC   ((\fBLPC_PMC_T\fP              *) \fBLPC_PMC_BASE\fP)"

.PP
Definición en la línea 121 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_PMC_BASE   0x40042000"

.PP
Definición en la línea 67 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_QEI   ((\fBLPC_QEI_T\fP              *) \fBLPC_QEI_BASE\fP)"

.PP
Definición en la línea 150 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_QEI_BASE   0x400C6000"

.PP
Definición en la línea 98 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_REGFILE   ((\fBLPC_REGFILE_T\fP          *) \fBLPC_REGFILE_BASE\fP)"

.PP
Definición en la línea 120 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_REGFILE_BASE   0x40041000"

.PP
Definición en la línea 66 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RGU   ((\fBLPC_RGU_T\fP              *) \fBLPC_RGU_BASE\fP)"

.PP
Definición en la línea 128 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RGU_BASE   0x40053000"

.PP
Definición en la línea 75 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RITIMER   ((\fBLPC_RITIMER_T\fP          *) \fBLPC_RITIMER_BASE\fP)"

.PP
Definición en la línea 149 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RITIMER_BASE   0x400C0000"

.PP
Definición en la línea 97 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ROM_API   ((\fBLPC_ROM_API_T\fP          *) \fBLPC_ROM_API_BASE\fP)"

.PP
Definición en la línea 160 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_ROM_API_BASE   0x10400100"

.PP
Definición en la línea 108 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RTC   ((\fBLPC_RTC_T\fP              *) \fBLPC_RTC_BASE\fP)"

.PP
Definición en la línea 123 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_RTC_BASE   0x40046000"

.PP
Definición en la línea 71 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SCT   ((\fBLPC_SCT_T\fP              *) \fBLPC_SCT_BASE\fP)"

.PP
Definición en la línea 110 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SCT_BASE   0x40000000"

.PP
Definición en la línea 54 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SCU   ((\fBLPC_SCU_T\fP              *) \fBLPC_SCU_BASE\fP)"

.PP
Definición en la línea 140 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SCU_BASE   0x40086000"

.PP
Definición en la línea 87 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SDMMC   ((\fBLPC_SDMMC_T\fP            *) \fBLPC_SDMMC_BASE\fP)"

.PP
Definición en la línea 113 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SDMMC_BASE   0x40004000"

.PP
Definición en la línea 57 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SGPIO_BASE   0x40101000"

.PP
Definición en la línea 106 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SPI_BASE   0x40100000"

.PP
Definición en la línea 105 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SPIFI   ((\fBLPC_SPIFI_T\fP            *) \fBLPC_SPIFI_BASE\fP)"

.PP
Definición en la línea 112 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SPIFI_BASE   0x40003000"

.PP
Definición en la línea 56 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SSP0   ((\fBLPC_SSP_T\fP              *) \fBLPC_SSP0_BASE\fP)"

.PP
Definición en la línea 134 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SSP0_BASE   0x40083000"

.PP
Definición en la línea 81 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SSP1   ((\fBLPC_SSP_T\fP              *) \fBLPC_SSP1_BASE\fP)"

.PP
Definición en la línea 135 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_SSP1_BASE   0x400C5000"

.PP
Definición en la línea 82 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER0   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER0_BASE\fP)"

.PP
Definición en la línea 136 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER0_BASE   0x40084000"

.PP
Definición en la línea 83 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER1   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER1_BASE\fP)"

.PP
Definición en la línea 137 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER1_BASE   0x40085000"

.PP
Definición en la línea 84 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER2   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER2_BASE\fP)"

.PP
Definición en la línea 138 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER2_BASE   0x400C3000"

.PP
Definición en la línea 85 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER3   ((\fBLPC_TIMER_T\fP            *) \fBLPC_TIMER3_BASE\fP)"

.PP
Definición en la línea 139 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_TIMER3_BASE   0x400C4000"

.PP
Definición en la línea 86 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_UART1   ((\fBLPC_USART_T\fP            *) \fBLPC_UART1_BASE\fP)"

.PP
Definición en la línea 133 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_UART1_BASE   0x40082000"

.PP
Definición en la línea 80 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART0   ((\fBLPC_USART_T\fP            *) \fBLPC_USART0_BASE\fP)"

.PP
Definición en la línea 130 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART0_BASE   0x40081000"

.PP
Definición en la línea 77 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART2   ((\fBLPC_USART_T\fP            *) \fBLPC_USART2_BASE\fP)"

.PP
Definición en la línea 131 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART2_BASE   0x400C1000"

.PP
Definición en la línea 78 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART3   ((\fBLPC_USART_T\fP            *) \fBLPC_USART3_BASE\fP)"

.PP
Definición en la línea 132 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USART3_BASE   0x400C2000"

.PP
Definición en la línea 79 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USB0   ((\fBLPC_USBHS_T\fP            *) \fBLPC_USB0_BASE\fP)"

.PP
Definición en la línea 115 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USB0_BASE   0x40006000"

.PP
Definición en la línea 59 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USB1   ((\fBLPC_USBHS_T\fP            *) \fBLPC_USB1_BASE\fP)"

.PP
Definición en la línea 116 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_USB1_BASE   0x40007000"

.PP
Definición en la línea 60 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_WWDT   ((\fBLPC_WWDT_T\fP             *) \fBLPC_WWDT_BASE\fP)"

.PP
Definición en la línea 129 del archivo chip_lpc18xx\&.h\&.
.SS "#define LPC_WWDT_BASE   0x40080000"

.PP
Definición en la línea 76 del archivo chip_lpc18xx\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
