.TH "PINMUX_GRP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PINMUX_GRP_T \- Array of pin definitions passed to \fBChip_SCU_SetPinMuxing()\fP must be in this format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scu_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBpingrp\fP"
.br
.ti -1c
.RI "uint8_t \fBpinnum\fP"
.br
.ti -1c
.RI "uint16_t \fBmodefunc\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Array of pin definitions passed to \fBChip_SCU_SetPinMuxing()\fP must be in this format\&. 
.PP
Definición en la línea 43 del archivo scu_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint16_t modefunc"

.PP
Definición en la línea 46 del archivo scu_18xx_43xx\&.h\&.
.SS "uint8_t pingrp"

.PP
Definición en la línea 44 del archivo scu_18xx_43xx\&.h\&.
.SS "uint8_t pinnum"

.PP
Definición en la línea 45 del archivo scu_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
