.TH "pmc_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmc_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_PMC_Sleep\fP (void)"
.br
.RI "\fISet to sleep power state\&. \fP"
.ti -1c
.RI "void \fBChip_PMC_Set_PwrState\fP (\fBCHIP_PMC_PWR_STATE_T\fP PwrState)"
.br
.RI "\fISet to sleep power mode\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
