.TH "pSDMMC_DMA_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pSDMMC_DMA_T \- SDIO chained DMA descriptor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sdif_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "volatile uint32_t \fBdes0\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBdes1\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBdes2\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBdes3\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
SDIO chained DMA descriptor\&. 
.PP
Definición en la línea 243 del archivo sdif_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "volatile uint32_t des0"
Control and status 
.PP
Definición en la línea 244 del archivo sdif_18xx_43xx\&.h\&.
.SS "volatile uint32_t des1"
Buffer size(s) 
.PP
Definición en la línea 245 del archivo sdif_18xx_43xx\&.h\&.
.SS "volatile uint32_t des2"
Buffer address pointer 1 
.PP
Definición en la línea 246 del archivo sdif_18xx_43xx\&.h\&.
.SS "volatile uint32_t des3"
Buffer address pointer 2 
.PP
Definición en la línea 247 del archivo sdif_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
