.TH "registro.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
registro.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br
\fC#include 'hardware\&.h'\fP
.br

.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBTEC1_IRQ\fP   1"
.br
.ti -1c
.RI "#define \fBTEC2_IRQ\fP   2"
.br
.ti -1c
.RI "#define \fBTEC3_IRQ\fP   3"
.br
.ti -1c
.RI "#define \fBTEC4_IRQ\fP   4"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBinit_interrupciones\fP (void)"
.br
.RI "\fIInicialización de interrupciones de los pulsadores\&. \fP"
.ti -1c
.RI "void \fBconfigurar_USART2\fP (void)"
.br
.RI "\fIConfigurar la USART2\&. \fP"
.ti -1c
.RI "void \fBconfigurar_SysTick\fP (void)"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define TEC1_IRQ   1"
\\ file test \&.h \\ brief Documentando header de \fBregistro\&.h\fP
.PP
Esta es la referencia extendida asodiada al header test \&.h 
.PP
Definición en la línea 11 del archivo registro\&.h\&.
.SS "#define TEC2_IRQ   2"

.PP
Definición en la línea 12 del archivo registro\&.h\&.
.SS "#define TEC3_IRQ   3"

.PP
Definición en la línea 13 del archivo registro\&.h\&.
.SS "#define TEC4_IRQ   4"

.PP
Definición en la línea 14 del archivo registro\&.h\&.
.SH "Documentación de las funciones"
.PP 
.SS "void configurar_SysTick (void)"

.PP
Definición en la línea 49 del archivo registro\&.c\&.
.SS "void configurar_USART2 (void)"

.PP
Configurar la USART2\&. 
.PP
Definición en la línea 40 del archivo registro\&.c\&.
.SS "void init_interrupciones (void)"

.PP
Inicialización de interrupciones de los pulsadores\&. TEC1, TEC2 y TEC4 
.PP
Definición en la línea 11 del archivo registro\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
