.TH "registro.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
registro.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'registro\&.h'\fP
.br
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBinit_interrupciones\fP ()"
.br
.RI "\fIInicialización de interrupciones de los pulsadores\&. \fP"
.ti -1c
.RI "void \fBconfigurar_USART2\fP ()"
.br
.RI "\fIConfigurar la USART2\&. \fP"
.ti -1c
.RI "void \fBconfigurar_SysTick\fP (void)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "void configurar_SysTick (void)"

.PP
Definición en la línea 49 del archivo registro\&.c\&.
.SS "void configurar_USART2 (void)"

.PP
Configurar la USART2\&. 
.PP
Definición en la línea 40 del archivo registro\&.c\&.
.SS "void init_interrupciones (void)"

.PP
Inicialización de interrupciones de los pulsadores\&. TEC1, TEC2 y TEC4 
.PP
Definición en la línea 11 del archivo registro\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
