.TH "RINGBUFF_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RINGBUFF_T \- Ring buffer structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ring_buffer\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBitemSz\fP"
.br
.ti -1c
.RI "uint32_t \fBhead\fP"
.br
.ti -1c
.RI "uint32_t \fBtail\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Ring buffer structure\&. 
.PP
Definición en la línea 45 del archivo ring_buffer\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "int count"

.PP
Definición en la línea 47 del archivo ring_buffer\&.h\&.
.SS "void* data"

.PP
Definición en la línea 46 del archivo ring_buffer\&.h\&.
.SS "uint32_t head"

.PP
Definición en la línea 49 del archivo ring_buffer\&.h\&.
.SS "int itemSz"

.PP
Definición en la línea 48 del archivo ring_buffer\&.h\&.
.SS "uint32_t tail"

.PP
Definición en la línea 50 del archivo ring_buffer\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
