.TH "ritimer_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ritimer_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_RIT_Init\fP (\fBLPC_RITIMER_T\fP *pRITimer)"
.br
.RI "\fIInitialize the RIT\&. \fP"
.ti -1c
.RI "void \fBChip_RIT_DeInit\fP (\fBLPC_RITIMER_T\fP *pRITimer)"
.br
.RI "\fIShutdown the RIT\&. \fP"
.ti -1c
.RI "void \fBChip_RIT_SetTimerInterval\fP (\fBLPC_RITIMER_T\fP *pRITimer, uint32_t time_interval)"
.br
.RI "\fISet timer interval value\&. \fP"
.ti -1c
.RI "\fBIntStatus\fP \fBChip_RIT_GetIntStatus\fP (\fBLPC_RITIMER_T\fP *pRITimer)"
.br
.RI "\fICheck whether interrupt flag is set or not\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
