.TH "RTC_EV_TIMESTAMP_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_EV_TIMESTAMP_T \- Event Monitor/Recorder Timestamp structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBsec\fP"
.br
.ti -1c
.RI "uint8_t \fBmin\fP"
.br
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.ti -1c
.RI "uint16_t \fBdayofyear\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Event Monitor/Recorder Timestamp structure\&. 
.PP
Definición en la línea 291 del archivo rtc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint16_t dayofyear"
Day of year 
.PP
Definición en la línea 295 del archivo rtc_18xx_43xx\&.h\&.
.SS "uint8_t hour"
Hour 
.PP
Definición en la línea 294 del archivo rtc_18xx_43xx\&.h\&.
.SS "uint8_t min"
Minute 
.PP
Definición en la línea 293 del archivo rtc_18xx_43xx\&.h\&.
.SS "uint8_t sec"
Second 
.PP
Definición en la línea 292 del archivo rtc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
