.TH "RTC_TIME_T" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_TIME_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rtc_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBtime\fP [\fBRTC_TIMETYPE_LAST\fP]"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 310 del archivo rtc_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint32_t time[\fBRTC_TIMETYPE_LAST\fP]"

.PP
Definición en la línea 311 del archivo rtc_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
