.TH "sct_pwm_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sct_pwm_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_SCTPWM_SetOutPin\fP (\fBLPC_SCT_T\fP *pSCT, uint8_t index, uint8_t pin)"
.br
.RI "\fISetup the OUTPUT pin and associate it with an index\&. \fP"
.ti -1c
.RI "void \fBChip_SCTPWM_SetRate\fP (\fBLPC_SCT_T\fP *pSCT, uint32_t freq)"
.br
.RI "\fISets the frequency of the generated PWM wave\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
