.TH "sct_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sct_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_SCT_Init\fP (\fBLPC_SCT_T\fP *pSCT)"
.br
.RI "\fIInitializes the State Configurable Timer\&. \fP"
.ti -1c
.RI "void \fBChip_SCT_DeInit\fP (\fBLPC_SCT_T\fP *pSCT)"
.br
.RI "\fIDeinitializes the State Configurable Timer\&. \fP"
.ti -1c
.RI "void \fBChip_SCT_SetClrControl\fP (\fBLPC_SCT_T\fP *pSCT, uint32_t value, \fBFunctionalState\fP ena)"
.br
.RI "\fISet or Clear the Control register\&. \fP"
.ti -1c
.RI "void \fBChip_SCT_SetConflictResolution\fP (\fBLPC_SCT_T\fP *pSCT, uint8_t outnum, uint8_t value)"
.br
.RI "\fISet the conflict resolution\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
