.TH "SGPIO_43XX" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SGPIO_43XX \- CHIP: LPC43xx Serial GPIO driverThis module is present in LPC43xx MCUs only\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
