.TH "SPI_Address_t" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Address_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssp_18xx_43xx\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBport\fP"
.br
.ti -1c
.RI "uint8_t \fBpin\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 462 del archivo ssp_18xx_43xx\&.h\&.
.SH "Documentación de los campos"
.PP 
.SS "uint8_t pin"
Pin number 
.PP
Definición en la línea 464 del archivo ssp_18xx_43xx\&.h\&.
.SS "uint8_t port"
Port Number 
.PP
Definición en la línea 463 del archivo ssp_18xx_43xx\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
