.TH "stopwatch.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stopwatch.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cmsis\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBStopWatch_Init\fP (void)"
.br
.RI "\fIInitialize stopwatch\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_Start\fP (void)"
.br
.RI "\fIStart a stopwatch\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP uint32_t \fBStopWatch_Elapsed\fP (uint32_t startTime)"
.br
.RI "\fIReturns number of ticks elapsed since stopwatch was started\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_TicksPerSecond\fP (void)"
.br
.RI "\fIReturns number of ticks per second of the stopwatch timer\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_TicksToMs\fP (uint32_t ticks)"
.br
.RI "\fIConverts from stopwatch ticks to mS\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_TicksToUs\fP (uint32_t ticks)"
.br
.RI "\fIConverts from stopwatch ticks to uS\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_MsToTicks\fP (uint32_t mS)"
.br
.RI "\fIConverts from mS to stopwatch ticks\&. \fP"
.ti -1c
.RI "uint32_t \fBStopWatch_UsToTicks\fP (uint32_t uS)"
.br
.RI "\fIConverts from uS to stopwatch ticks\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBStopWatch_DelayTicks\fP (uint32_t ticks)"
.br
.RI "\fIDelays the given number of ticks using stopwatch primitives\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBStopWatch_DelayMs\fP (uint32_t mS)"
.br
.RI "\fIDelays the given number of mS using stopwatch primitives\&. \fP"
.ti -1c
.RI "\fBSTATIC\fP \fBINLINE\fP void \fBStopWatch_DelayUs\fP (uint32_t uS)"
.br
.RI "\fIDelays the given number of uS using stopwatch primitives\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
