.TH "SUPPORT_18XX_43XX_FUNC" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SUPPORT_18XX_43XX_FUNC \- CHIP: LPC18xx/43xx support functions
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBSystemCoreClockUpdate\fP (void)"
.br
.RI "\fIUpdate system core clock rate, should be called if the system has a clock rate change\&. \fP"
.ti -1c
.RI "void \fBChip_USB0_Init\fP (void)"
.br
.RI "\fIUSB0 Pin and clock initialization Calling this function will initialize the USB0 pins and the clock\&. \fP"
.ti -1c
.RI "void \fBChip_USB1_Init\fP (void)"
.br
.RI "\fIUSB1 Pin and clock initialization Calling this function will initialize the USB0 pins and the clock\&. \fP"
.ti -1c
.RI "void \fBChip_SystemInit\fP (void)"
.br
.RI "\fISet up and initialize hardware prior to call to \fBmain()\fP \fP"
.ti -1c
.RI "void \fBChip_SetupCoreClock\fP (\fBCHIP_CGU_CLKIN_T\fP clkin, uint32_t core_freq, bool setbase)"
.br
.RI "\fIClock and PLL initialization based input given in \fIclkin\fP\&. \fP"
.ti -1c
.RI "void \fBChip_SetupXtalClocking\fP (void)"
.br
.RI "\fIClock and PLL initialization based on the external oscillator\&. \fP"
.ti -1c
.RI "void \fBChip_SetupIrcClocking\fP (void)"
.br
.RI "\fIClock and PLL initialization based on the internal oscillator\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP"
.br
.RI "\fICurrent system clock rate, mainly used for sysTick\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de las funciones"
.PP 
.SS "void Chip_SetupCoreClock (\fBCHIP_CGU_CLKIN_T\fP clkin, uint32_t core_freq, bool setbase)"

.PP
Clock and PLL initialization based input given in \fIclkin\fP\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIclkin\fP : Input reference clock to PLL1 (MAINPLL) see \fBCHIP_CGU_CLKIN_T\fP 
.br
\fIcore_freq\fP : Desired output frequency of the PLL1 (Base clock to CPU Core) 
.br
\fIsetbase\fP : Setup default base clock of peripherals (see notes) 
.RE
.PP
\fBDevuelve:\fP
.RS 4
None 
.RE
.PP
\fBNota:\fP
.RS 4
This API will initialize the MAINPLL (PLL1) to the frequency given by \fIcore_freq\fP, and will use this PLL's output as the base clock for CPU Core\&. If \fIclkin\fP is \fBCLKIN_CRYSTAL\fP then External Crystal Oscillator of frequency 12MHz will be used as the input reference clock to PLL1\&.
.br
 Parameter \fIsetbase\fP if true will set APB[1,3], SSP[0,1], UART[0,1,2,3], SPI base clocks to MAINPLL's output clock\&. If \fIsetbase\fP is false then the base clock settings for the peripherals will not be modified, only CPU Core's base clock will be updated to use clock generated by PLL1\&. 
.RE
.PP

.PP
Definición en la línea 81 del archivo sysinit_18xx_43xx\&.c\&.
.SS "void Chip_SetupIrcClocking (void)"

.PP
Clock and PLL initialization based on the internal oscillator\&. 
.PP
\fBDevuelve:\fP
.RS 4
None 
.RE
.PP
\fBNota:\fP
.RS 4
This API will initialize the MAINPLL (PLL1) to the maximum frequency (180MHz[LPC18xx] or 204MHz[LPC43xx]) and uses this PLL's output as the base clock for CPU Core\&. Internal RC Oscillator will be used as the input reference clock to PLL1\&. 
.RE
.PP

.PP
Definición en la línea 150 del archivo sysinit_18xx_43xx\&.c\&.
.SS "void Chip_SetupXtalClocking (void)"

.PP
Clock and PLL initialization based on the external oscillator\&. 
.PP
\fBDevuelve:\fP
.RS 4
None 
.RE
.PP
\fBNota:\fP
.RS 4
This API will initialize the MAINPLL (PLL1) to the maximum frequency (180MHz[LPC18xx] or 204MHz[LPC43xx]) and uses this PLL's output as the base clock for CPU Core\&. External Crystal Oscillator of frequency 12MHz will be used as the input reference clock to PLL1\&. 
.RE
.PP

.PP
Definición en la línea 144 del archivo sysinit_18xx_43xx\&.c\&.
.SS "void Chip_SystemInit (void)"

.PP
Set up and initialize hardware prior to call to \fBmain()\fP 
.PP
\fBDevuelve:\fP
.RS 4
None 
.RE
.PP
\fBNota:\fP
.RS 4
\fBChip_SystemInit()\fP is called prior to the application and sets up system clocking prior to the application starting\&. 
.RE
.PP

.PP
Definición en la línea 156 del archivo sysinit_18xx_43xx\&.c\&.
.SS "void Chip_USB0_Init (void)"

.PP
USB0 Pin and clock initialization Calling this function will initialize the USB0 pins and the clock\&. 
.PP
\fBNota:\fP
.RS 4
This function will assume that the chip is clocked by an external crystal oscillator of frequency 12MHz 
.RE
.PP

.PP
Definición en la línea 76 del archivo chip_18xx_43xx\&.c\&.
.SS "void Chip_USB1_Init (void)"

.PP
USB1 Pin and clock initialization Calling this function will initialize the USB0 pins and the clock\&. 
.PP
\fBNota:\fP
.RS 4
This function will assume that the chip is clocked by an external crystal oscillator of frequency 12MHz 
.RE
.PP

.PP
Definición en la línea 91 del archivo chip_18xx_43xx\&.c\&.
.SS "void SystemCoreClockUpdate (void)"

.PP
Update system core clock rate, should be called if the system has a clock rate change\&. 
.PP
\fBDevuelve:\fP
.RS 4
None 
.RE
.PP

.PP
Definición en la línea 113 del archivo chip_18xx_43xx\&.c\&.
.SH "Documentación de las variables"
.PP 
.SS "uint32_t SystemCoreClock"

.PP
Current system clock rate, mainly used for sysTick\&. 
.PP
Definición en la línea 50 del archivo chip_18xx_43xx\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
