.TH "utils.h" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.h \- Diversas funciones de utilidad simplificar el desarrollo de software para aplicaciones embebidas\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBprint\fP (char *msg)"
.br
.RI "\fIEnvía una cadena de caracteres terminada en null por el puerto de comunicaciones serie (USART)\&. \fP"
.ti -1c
.RI "void \fBerror\fP (char *msg)"
.br
.RI "\fIEnvía una cadena de caracteres terminada en null por el puerto de comunicaciones serie (USART)\&. A diferencia de la función \fBprint\fP, esta función no retorna bloqueando la aplicación\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Diversas funciones de utilidad simplificar el desarrollo de software para aplicaciones embebidas\&. 


.PP
\fBFecha:\fP
.RS 4
09/07/2018 
.RE
.PP

.PP
Definición en el archivo \fButils\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
