.TH "utils.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBprint\fP (char *msg)"
.br
.RI "\fIEnvía una cadena de caracteres terminada en null por el puerto de comunicaciones serie (USART)\&. \fP"
.ti -1c
.RI "void \fBerror\fP (char *msg)"
.br
.RI "\fIEnvía una cadena de caracteres terminada en null por el puerto de comunicaciones serie (USART)\&. A diferencia de la función \fBprint\fP, esta función no retorna bloqueando la aplicación\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
