.TH "wwdt_18xx_43xx.c" 3 "Viernes, 14 de Septiembre de 2018" "Ejercicio 1 - TP 5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wwdt_18xx_43xx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chip\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBChip_WWDT_Init\fP (\fBLPC_WWDT_T\fP *pWWDT)"
.br
.RI "\fIInitialize the Watchdog timer\&. \fP"
.ti -1c
.RI "void \fBChip_WWDT_DeInit\fP (\fBLPC_WWDT_T\fP *pWWDT)"
.br
.RI "\fIShutdown the Watchdog timer\&. \fP"
.ti -1c
.RI "void \fBChip_WWDT_ClearStatusFlag\fP (\fBLPC_WWDT_T\fP *pWWDT, uint32_t status)"
.br
.RI "\fIClear WWDT interrupt status flags\&. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Ejercicio 1 - TP 5 del código fuente\&.
